//Meta Search and Control Center (c) 2026 Dennis Michael Heine
namespace MSCC.Localization;

/// <summary>
/// Englische �bersetzungen (Standard/Fallback).
/// </summary>
public static class Strings_en
{
    public static Dictionary<string, string> Resources { get; } = new()
    {
        // Application
        ["AppTitle"] = "MSCC - Meta Search Command Center",
        ["Ready"] = "Ready",
        ["Error"] = "Error",
        ["Warning"] = "Warning",
        ["Success"] = "Success",
        ["Cancel"] = "Cancel",
        ["Save"] = "Save",
        ["Delete"] = "Delete",
        ["Edit"] = "Edit",
        ["Add"] = "Add",
        ["Close"] = "Close",
        ["Yes"] = "Yes",
        ["No"] = "No",
        ["OK"] = "OK",

        // Menu
        ["MenuFile"] = "File",
        ["MenuExit"] = "Exit",
        ["MenuPlugins"] = "Plugins",
        ["MenuScriptManager"] = "Script Manager...",
        ["MenuReloadScripts"] = "Reload Scripts",
        ["MenuSettings"] = "Settings...",
        ["MenuHelp"] = "Help",
        ["MenuAbout"] = "About MSCC",

        // Search
        ["Search"] = "Search",
        ["SearchResults"] = "Search Results",
        ["Searching"] = "Searching...",
        ["SearchCompleted"] = "Search completed",
        ["NoResults"] = "No results found",
        ["ResultsFound"] = "{0} results found",
        ["Source"] = "Source",

        // DataSources
        ["DataSources"] = "Data Sources",
        ["NewDataSource"] = "New Data Source",
        ["EditDataSource"] = "Edit Data Source",
        ["DeleteDataSource"] = "Delete Data Source",
        ["DataSourceName"] = "Name",
        ["ConnectorType"] = "Connector Type",
        ["Configuration"] = "Configuration",
        ["Enabled"] = "Enabled",
        ["NoDataSourcesSelected"] = "No data sources selected or available",

        // Groups
        ["Groups"] = "Groups",
        ["NewGroup"] = "New Group",
        ["EditGroup"] = "Edit Group",
        ["DeleteGroup"] = "Delete Group",
        ["GroupName"] = "Name",
        ["GroupColor"] = "Color",
        ["NoGroup"] = "(No Group)",

        // Details
        ["DetailView"] = "Detail View",
        ["SelectResultForDetails"] = "Select a search result to view details.",
        ["Open"] = "Open",
        ["OpenFolder"] = "Open Folder",
        ["CopyPath"] = "Copy Path",

        // Labels
        ["AddLabel"] = "Add Label",
        ["SelectResultFirst"] = "Select a result first",
        ["KeywordSearch"] = "Keyword Search",
        ["SearchByKeyword"] = "Search by Keyword",
        ["CurrentQuery"] = "Current Query",
        ["SavedQueries"] = "Saved Queries",
        ["Load"] = "Load",
        ["Labels"] = "Labels",

        // Script Editor
        ["ScriptEditor"] = "Script Editor",
        ["ScriptManager"] = "Script Manager",
        ["NewScript"] = "New Script",
        ["Compile"] = "Compile",
        ["Validate"] = "Validate",
        ["Insert"] = "Insert",
        ["Errors"] = "Errors",
        ["Warnings"] = "Warnings",
        ["Line"] = "Line",
        ["Column"] = "Column",
        ["CompileSuccess"] = "Compilation successful - Connector registered",
        ["CompileFailed"] = "Compilation failed - {0} errors",

        // Settings
        ["Settings"] = "Settings",
        ["Language"] = "Language",
        ["SelectLanguage"] = "Select Language",
        ["RestartRequired"] = "Some changes require a restart to take effect.",
        ["General"] = "General",
        ["Appearance"] = "Appearance",

        // Validation
        ["FieldRequired"] = "The field '{0}' is required.",
        ["InvalidValue"] = "Invalid value",
        ["ValidationError"] = "Validation Error",

        // Status
        ["Loading"] = "Loading...",
        ["Saving"] = "Saving...",
        ["Compiling"] = "Compiling...",
        ["ScriptConnectorsLoaded"] = "{0} script connectors loaded",
        ["DataSourceCreated"] = "Data source '{0}' created",
        ["DataSourceUpdated"] = "Data source '{0}' updated",
        ["DataSourceDeleted"] = "Data source '{0}' deleted",
        ["GroupCreated"] = "Group '{0}' created",
        ["GroupUpdated"] = "Group '{0}' updated",
        ["GroupDeleted"] = "Group '{0}' deleted",

        // Confirmation dialogs
        ["ConfirmDelete"] = "Are you sure you want to delete '{0}'?",
        ["ConfirmDeleteDataSource"] = "Do you really want to delete the data source '{0}'?",
        ["ConfirmDeleteGroup"] = "Do you really want to delete the group '{0}'?\n\nData sources in this group will not be deleted.",

        // === Connector: FileSystem ===
        ["Connector_FileSystem_Name"] = "File System",
        ["Connector_FileSystem_Description"] = "Searches files and folders in the local file system.",
        ["Connector_FileSystem_BasePath"] = "Base Path",
        ["Connector_FileSystem_BasePath_Desc"] = "The folder path to search.",
        ["Connector_FileSystem_SearchPattern"] = "Search Pattern",
        ["Connector_FileSystem_SearchPattern_Desc"] = "File pattern (e.g., *.txt, *.pdf)",
        ["Connector_FileSystem_IncludeSubdirs"] = "Include Subdirectories",
        ["Connector_FileSystem_IncludeSubdirs_Desc"] = "Specifies whether subdirectories should be searched.",
        ["Connector_FileSystem_Open"] = "Open",
        ["Connector_FileSystem_Open_Desc"] = "Open file with default program",
        ["Connector_FileSystem_OpenFolder"] = "Open Folder",
        ["Connector_FileSystem_OpenFolder_Desc"] = "Open containing folder",
        ["Connector_FileSystem_CopyPath"] = "Copy Path",
        ["Connector_FileSystem_CopyPath_Desc"] = "Copy file path to clipboard",
        ["Connector_FileSystem_Path"] = "Path",
        ["Connector_FileSystem_Size"] = "Size",
        ["Connector_FileSystem_Created"] = "Created",
        ["Connector_FileSystem_Modified"] = "Modified",
        ["Connector_FileSystem_Type"] = "Type",

        // === Connector: DuckDuckGo ===
        ["Connector_DuckDuckGo_Name"] = "DuckDuckGo Web Search",
        ["Connector_DuckDuckGo_Description"] = "Performs web searches via DuckDuckGo.",
        ["Connector_DuckDuckGo_MaxResults"] = "Max Results",
        ["Connector_DuckDuckGo_MaxResults_Desc"] = "Number of search results to return (1-30).",
        ["Connector_DuckDuckGo_Region"] = "Region",
        ["Connector_DuckDuckGo_Region_Desc"] = "Region setting for search results (e.g., 'de-de' for Germany, 'wt-wt' for worldwide).",
        ["Connector_DuckDuckGo_SafeSearch"] = "SafeSearch",
        ["Connector_DuckDuckGo_SafeSearch_Desc"] = "Enables SafeSearch filter for family-friendly results.",
        ["Connector_DuckDuckGo_OpenBrowser"] = "Open in Browser",
        ["Connector_DuckDuckGo_OpenBrowser_Desc"] = "Open webpage in default browser",
        ["Connector_DuckDuckGo_CopyUrl"] = "Copy URL",
        ["Connector_DuckDuckGo_CopyUrl_Desc"] = "Copy URL to clipboard",
        ["Connector_DuckDuckGo_SearchMore"] = "Search on DuckDuckGo",
        ["Connector_DuckDuckGo_SearchMore_Desc"] = "Show more results on DuckDuckGo",
        ["Connector_DuckDuckGo_WebResult"] = "Web Search Result",
        ["Connector_DuckDuckGo_Position"] = "Position",

        // === Connector: Microsoft 365 ===
        ["Connector_M365_Name"] = "Microsoft 365",
        ["Connector_M365_Description"] = "Searches Microsoft 365: Calendar, ToDo, Emails, and OneNote.",
        ["Connector_M365_ClientId"] = "Client ID (App-ID)",
        ["Connector_M365_ClientId_Desc"] = "The Application (Client) ID from your Azure app registration.",
        ["Connector_M365_TenantId"] = "Tenant ID",
        ["Connector_M365_TenantId_Desc"] = "The Tenant ID (or 'common' for multi-tenant, 'consumers' for personal accounts).",
        ["Connector_M365_SearchCalendar"] = "Search Calendar",
        ["Connector_M365_SearchCalendar_Desc"] = "Include calendar events in search.",
        ["Connector_M365_SearchToDo"] = "Search ToDo",
        ["Connector_M365_SearchToDo_Desc"] = "Include Microsoft ToDo tasks in search.",
        ["Connector_M365_SearchMail"] = "Search Email",
        ["Connector_M365_SearchMail_Desc"] = "Include emails in search.",
        ["Connector_M365_SearchOneNote"] = "Search OneNote",
        ["Connector_M365_SearchOneNote_Desc"] = "Include OneNote pages in search.",
        ["Connector_M365_MaxDaysBack"] = "Max Days Back",
        ["Connector_M365_MaxDaysBack_Desc"] = "How many days back to search for calendar events and emails.",
        ["Connector_M365_OpenOutlook"] = "Open in Outlook",
        ["Connector_M365_OpenOutlook_Desc"] = "Open in Outlook Web",
        ["Connector_M365_OpenToDo"] = "Open in ToDo",
        ["Connector_M365_OpenToDo_Desc"] = "Open task in Microsoft ToDo",
        ["Connector_M365_OpenOneNote"] = "Open in OneNote",
        ["Connector_M365_OpenOneNote_Desc"] = "Open page in OneNote",
        ["Connector_M365_CopyLink"] = "Copy Link",
        ["Connector_M365_CopyLink_Desc"] = "Copy link to clipboard",
        ["Connector_M365_OpenBrowser"] = "Open in Browser",
        ["Connector_M365_OpenBrowser_Desc"] = "Open in default browser",
        ["Connector_M365_CalendarEntry"] = "Calendar Entry",
        ["Connector_M365_Task"] = "Task",
        ["Connector_M365_Email"] = "Email",
        ["Connector_M365_OneNotePage"] = "OneNote Page",
        ["Connector_M365_Subject"] = "Subject",
        ["Connector_M365_Start"] = "Start",
        ["Connector_M365_End"] = "End",
        ["Connector_M365_Location"] = "Location",
        ["Connector_M365_Organizer"] = "Organizer",
        ["Connector_M365_List"] = "List",
        ["Connector_M365_Status"] = "Status",
        ["Connector_M365_Priority"] = "Priority",
        ["Connector_M365_DueDate"] = "Due Date",
        ["Connector_M365_Notes"] = "Notes",
        ["Connector_M365_From"] = "From",
        ["Connector_M365_Received"] = "Received",
        ["Connector_M365_Attachments"] = "Attachments",
        ["Connector_M365_Preview"] = "Preview",
        ["Connector_M365_Title"] = "Title",
        ["Connector_M365_Section"] = "Section",

        // === Connector: SQL Database ===
        ["Connector_SQL_Name"] = "SQL Database",
        ["Connector_SQL_Description"] = "Searches SQL databases (MySQL, MSSQL, PostgreSQL).",
        ["Connector_SQL_ConnectionString"] = "Connection String",
        ["Connector_SQL_ConnectionString_Desc"] = "Database connection string (e.g., 'Server=localhost;Database=mydb;User Id=user;Password=pass;')",
        ["Connector_SQL_DatabaseType"] = "Database Type",
        ["Connector_SQL_DatabaseType_Desc"] = "Type of database: MSSQL, MySQL, or PostgreSQL",
        ["Connector_SQL_Tables"] = "Tables",
        ["Connector_SQL_Tables_Desc"] = "Comma-separated list of tables to search, or '*' for all tables. Ignored if custom query is provided.",
        ["Connector_SQL_CustomQuery"] = "Custom SQL Query",
        ["Connector_SQL_CustomQuery_Desc"] = "Optional: Custom SELECT statement. Use @SearchTerm as placeholder for the search term.",
        ["Connector_SQL_CopyJson"] = "Copy as JSON",
        ["Connector_SQL_CopyJson_Desc"] = "Copy record as JSON to clipboard",
        ["Connector_SQL_CopyInsert"] = "Copy as INSERT",
        ["Connector_SQL_CopyInsert_Desc"] = "Copy as SQL INSERT statement",
        ["Connector_SQL_MatchesIn"] = "Matches in",
        ["Connector_SQL_Record"] = "Record",

        // === Connector: OpenAI ===
        ["OpenAiConnectorName"] = "OpenAI API",
        ["OpenAiConnectorDescription"] = "Queries OpenAI-compatible AI APIs (ChatGPT, local LLMs, etc.).",
        ["OpenAiApiEndpoint"] = "API Endpoint",
        ["OpenAiApiEndpointDesc"] = "The URL of the API endpoint (e.g., https://api.openai.com/v1/chat/completions)",
        ["OpenAiApiKey"] = "API Key",
        ["OpenAiApiKeyDesc"] = "Your API authentication token.",
        ["OpenAiModel"] = "Model",
        ["OpenAiModelDesc"] = "The AI model to use (e.g., gpt-3.5-turbo, gpt-4, llama2).",
        ["OpenAiSystemPrompt"] = "System Prompt",
        ["OpenAiSystemPromptDesc"] = "Optional system prompt to set the AI's behavior.",
        ["OpenAiMaxTokens"] = "Max Tokens",
        ["OpenAiMaxTokensDesc"] = "Maximum number of tokens in the response (1-128000).",
        ["OpenAiTemperature"] = "Temperature",
        ["OpenAiTemperatureDesc"] = "Creativity of responses (0.0 = deterministic, 2.0 = very creative).",
        ["OpenAiResponse"] = "AI Response",
        ["OpenAiError"] = "API Error",
        ["OpenAiErrorDesc"] = "Error during API request",
        ["OpenAiMetaModel"] = "Model",
        ["OpenAiMetaPromptTokens"] = "Prompt Tokens",
        ["OpenAiMetaCompletionTokens"] = "Completion Tokens",
        ["OpenAiMetaTotalTokens"] = "Total Tokens",
        ["OpenAiMetaFinishReason"] = "Finish Reason",
        ["OpenAiMetaQuery"] = "Query",
        ["OpenAiActionCopyResponse"] = "Copy Response",
        ["OpenAiActionCopyResponseDesc"] = "Copy the AI response to clipboard",
        ["OpenAiActionCopyQuery"] = "Copy Query",
        ["OpenAiActionCopyQueryDesc"] = "Copy the original query to clipboard",

        // === Connector: Generic API ===
        ["GenericApiConnectorName"] = "Generic API",
        ["GenericApiConnectorDescription"] = "Connects to any REST API with flexible authentication and search parameter placement.",
        ["GenericApiEndpoint"] = "API Endpoint",
        ["GenericApiEndpointDesc"] = "The base URL of the API. Use [SEARCH] as placeholder for the search term.",
        ["GenericApiHttpMethod"] = "HTTP Method",
        ["GenericApiHttpMethodDesc"] = "HTTP method to use: GET, POST, PUT, PATCH, DELETE",
        ["GenericApiAuthType"] = "Authentication Type",
        ["GenericApiAuthTypeDesc"] = "Authentication method: None, Header, Bearer, OAuth2, JWT, Query, Post",
        ["GenericApiAuthHeaderName"] = "Auth Header Name",
        ["GenericApiAuthHeaderNameDesc"] = "Name of the authentication header (e.g., Authorization, X-API-Key)",
        ["GenericApiAuthHeaderValue"] = "Auth Header Value",
        ["GenericApiAuthHeaderValueDesc"] = "Value for the authentication header",
        ["GenericApiAuthToken"] = "Auth Token",
        ["GenericApiAuthTokenDesc"] = "Authentication token for Bearer/JWT auth, or key=value for Query/Post parameter auth",
        ["GenericApiOAuth2TokenEndpoint"] = "OAuth2 Token Endpoint",
        ["GenericApiOAuth2TokenEndpointDesc"] = "URL to obtain OAuth2 access token",
        ["GenericApiOAuth2ClientId"] = "OAuth2 Client ID",
        ["GenericApiOAuth2ClientIdDesc"] = "Client ID for OAuth2 authentication",
        ["GenericApiOAuth2ClientSecret"] = "OAuth2 Client Secret",
        ["GenericApiOAuth2ClientSecretDesc"] = "Client Secret for OAuth2 authentication",
        ["GenericApiOAuth2Scope"] = "OAuth2 Scope",
        ["GenericApiOAuth2ScopeDesc"] = "OAuth2 scope (optional)",
        ["GenericApiQueryParameters"] = "Query Parameters",
        ["GenericApiQueryParametersDesc"] = "URL query parameters. Use [SEARCH] for search term (e.g., q=[SEARCH]&limit=10)",
        ["GenericApiPostBody"] = "POST Body",
        ["GenericApiPostBodyDesc"] = "Request body for POST/PUT/PATCH. Use [SEARCH] for search term.",
        ["GenericApiContentType"] = "Content Type",
        ["GenericApiContentTypeDesc"] = "Content-Type header for request body (e.g., application/json)",
        ["GenericApiCustomHeaders"] = "Custom Headers",
        ["GenericApiCustomHeadersDesc"] = "Additional headers, one per line (format: Header-Name: value)",
        ["GenericApiResultJsonPath"] = "Result JSON Path",
        ["GenericApiResultJsonPathDesc"] = "JSON path to results array (e.g., data.results)",
        ["GenericApiResultTitleProperty"] = "Title Property",
        ["GenericApiResultTitlePropertyDesc"] = "JSON property name for result title",
        ["GenericApiResultDescriptionProperty"] = "Description Property",
        ["GenericApiResultDescriptionPropertyDesc"] = "JSON property name for result description",
        ["GenericApiResultUrlProperty"] = "URL Property",
        ["GenericApiResultUrlPropertyDesc"] = "JSON property name for result URL",
        ["GenericApiTimeout"] = "Timeout (seconds)",
        ["GenericApiTimeoutDesc"] = "Request timeout in seconds (1-300)",
        ["GenericApiError"] = "API Error",
        ["GenericApiRawResponse"] = "Raw Response",
        ["GenericApiMetaQuery"] = "Query",
        ["GenericApiActionOpenUrl"] = "Open URL",
        ["GenericApiActionOpenUrlDesc"] = "Open result URL in browser",
        ["GenericApiActionCopyJson"] = "Copy as JSON",
        ["GenericApiActionCopyJsonDesc"] = "Copy result data as JSON",
        ["GenericApiActionCopyUrl"] = "Copy URL",
        ["GenericApiActionCopyUrlDesc"] = "Copy URL to clipboard",

        // === Connector: IMAP ===
        ["ImapConnectorName"] = "IMAP Email",
        ["ImapConnectorDescription"] = "Searches emails via IMAP protocol. Supports OAuth2 and password authentication.",
        ["ImapServer"] = "IMAP Server",
        ["ImapServerDesc"] = "IMAP server hostname (e.g., imap.gmail.com, outlook.office365.com)",
        ["ImapPort"] = "Port",
        ["ImapPortDesc"] = "IMAP server port (usually 993 for SSL/TLS, 143 for STARTTLS)",
        ["ImapEmailAddress"] = "Email Address",
        ["ImapEmailAddressDesc"] = "Your email address for authentication",
        ["ImapAuthType"] = "Authentication Type",
        ["ImapAuthTypeDesc"] = "Authentication method: Password or OAuth2",
        ["ImapPassword"] = "Password",
        ["ImapPasswordDesc"] = "Password or app-specific password for authentication",
        ["ImapOAuth2Token"] = "OAuth2 Access Token",
        ["ImapOAuth2TokenDesc"] = "OAuth2 access token for authentication (required if Auth Type is OAuth2)",
        ["ImapEncryption"] = "Encryption",
        ["ImapEncryptionDesc"] = "Encryption method: SslTls (recommended), StartTls, or None",
        ["ImapFolderName"] = "Folder",
        ["ImapFolderNameDesc"] = "Mail folder to search (e.g., INBOX, Sent, Archive)",
        ["ImapMaxResults"] = "Max Results",
        ["ImapMaxResultsDesc"] = "Maximum number of emails to return (1-500)",
        ["ImapMaxDaysBack"] = "Max Days Back",
        ["ImapMaxDaysBackDesc"] = "How many days back to search for emails (1-365)",
        ["ImapNoSubject"] = "(No Subject)",
        ["ImapError"] = "IMAP Error",
        ["ImapErrorDesc"] = "Error connecting to IMAP server",
        ["ImapMetaFrom"] = "From",
        ["ImapMetaFromEmail"] = "From (Email)",
        ["ImapMetaSubject"] = "Subject",
        ["ImapMetaDate"] = "Date",
        ["ImapMetaHasAttachments"] = "Attachments",
        ["ImapMetaFolder"] = "Folder",
        ["ImapActionCopyBody"] = "Copy Body",
        ["ImapActionCopyBodyDesc"] = "Copy email body to clipboard",
        ["ImapActionCopySender"] = "Copy Sender",
        ["ImapActionCopySenderDesc"] = "Copy sender email address to clipboard",
    };
}
