// Meta Search and Control Center (c) 2026 Dennis Michael Heine
namespace MSCC.Localization;

/// <summary>
/// Traductions fran\u00e7aises.
/// </summary>
public static class Strings_fr
{
    public static Dictionary<string, string> Resources { get; } = new()
    {
        // Application
        ["AppTitle"] = "MSCC - Centre de Commande de M\u00e9ta Recherche",
        ["Ready"] = "Pr\u00eat",
        ["Error"] = "Erreur",
        ["Warning"] = "Avertissement",
        ["Success"] = "Succ\u00e8s",
        ["Cancel"] = "Annuler",
        ["Save"] = "Enregistrer",
        ["Delete"] = "Supprimer",
        ["Edit"] = "Modifier",
        ["Add"] = "Ajouter",
        ["Close"] = "Fermer",
        ["Yes"] = "Oui",
        ["No"] = "Non",
        ["OK"] = "OK",

        // Menu
        ["MenuFile"] = "Fichier",
        ["MenuExit"] = "Quitter",
        ["MenuPlugins"] = "Plugins",
        ["MenuScriptManager"] = "Gestionnaire de Scripts...",
        ["MenuReloadScripts"] = "Recharger les Scripts",
        ["MenuSettings"] = "Param\u00e8tres...",
        ["MenuHelp"] = "Aide",
        ["MenuAbout"] = "\u00c0 propos de MSCC",

        // Search
        ["Search"] = "Rechercher",
        ["SearchResults"] = "R\u00e9sultats de Recherche",
        ["Searching"] = "Recherche en cours...",
        ["SearchCompleted"] = "Recherche termin\u00e9e",
        ["NoResults"] = "Aucun r\u00e9sultat trouv\u00e9",
        ["ResultsFound"] = "{0} r\u00e9sultats trouv\u00e9s",
        ["Source"] = "Source",

        // DataSources
        ["DataSources"] = "Sources de Donn\u00e9es",
        ["NewDataSource"] = "Nouvelle Source de Donn\u00e9es",
        ["EditDataSource"] = "Modifier la Source de Donn\u00e9es",
        ["DeleteDataSource"] = "Supprimer la Source de Donn\u00e9es",
        ["DataSourceName"] = "Nom",
        ["ConnectorType"] = "Type de Connecteur",
        ["Configuration"] = "Configuration",
        ["Enabled"] = "Activ\u00e9",
        ["NoDataSourcesSelected"] = "Aucune source de donn\u00e9es s\u00e9lectionn\u00e9e ou disponible",

        // Groups
        ["Groups"] = "Groupes",
        ["NewGroup"] = "Nouveau Groupe",
        ["EditGroup"] = "Modifier le Groupe",
        ["DeleteGroup"] = "Supprimer le Groupe",
        ["GroupName"] = "Nom",
        ["GroupColor"] = "Couleur",
        ["NoGroup"] = "(Aucun Groupe)",

        // Details
        ["DetailView"] = "Vue D\u00e9taill\u00e9e",
        ["SelectResultForDetails"] = "S\u00e9lectionnez un r\u00e9sultat pour afficher les d\u00e9tails.",
        ["Open"] = "Ouvrir",
        ["OpenFolder"] = "Ouvrir le Dossier",
        ["CopyPath"] = "Copier le Chemin",

        // Labels
        ["AddLabel"] = "Ajouter une \u00c9tiquette",
        ["SelectResultFirst"] = "S\u00e9lectionnez d'abord un r\u00e9sultat",
        ["KeywordSearch"] = "Recherche par Mot-cl\u00e9",
        ["SearchByKeyword"] = "Rechercher par Mot-cl\u00e9",
        ["CurrentQuery"] = "Requ\u00eate Actuelle",
        ["SavedQueries"] = "Requ\u00eates Enregistr\u00e9es",
        ["Load"] = "Charger",
        ["Labels"] = "\u00c9tiquettes",

        // Script Editor
        ["ScriptEditor"] = "\u00c9diteur de Scripts",
        ["ScriptManager"] = "Gestionnaire de Scripts",
        ["NewScript"] = "Nouveau Script",
        ["Compile"] = "Compiler",
        ["Validate"] = "Valider",
        ["Insert"] = "Ins\u00e9rer",
        ["Errors"] = "Erreurs",
        ["Warnings"] = "Avertissements",
        ["Line"] = "Ligne",
        ["Column"] = "Colonne",
        ["CompileSuccess"] = "Compilation r\u00e9ussie - Connecteur enregistr\u00e9",
        ["CompileFailed"] = "\u00c9chec de la compilation - {0} erreurs",

        // Settings
        ["Settings"] = "Param\u00e8tres",
        ["Language"] = "Langue",
        ["SelectLanguage"] = "S\u00e9lectionner la Langue",
        ["RestartRequired"] = "Certains changements n\u00e9cessitent un red\u00e9marrage.",
        ["General"] = "G\u00e9n\u00e9ral",
        ["Appearance"] = "Apparence",

        // Validation
        ["FieldRequired"] = "Le champ '{0}' est obligatoire.",
        ["InvalidValue"] = "Valeur invalide",
        ["ValidationError"] = "Erreur de Validation",

        // Status
        ["Loading"] = "Chargement...",
        ["Saving"] = "Enregistrement...",
        ["Compiling"] = "Compilation...",
        ["ScriptConnectorsLoaded"] = "{0} connecteurs de script charg\u00e9s",
        ["DataSourceCreated"] = "Source de donn\u00e9es '{0}' cr\u00e9\u00e9e",
        ["DataSourceUpdated"] = "Source de donn\u00e9es '{0}' mise \u00e0 jour",
        ["DataSourceDeleted"] = "Source de donn\u00e9es '{0}' supprim\u00e9e",
        ["GroupCreated"] = "Groupe '{0}' cr\u00e9\u00e9",
        ["GroupUpdated"] = "Groupe '{0}' mis \u00e0 jour",
        ["GroupDeleted"] = "Groupe '{0}' supprim\u00e9",

        // Confirmation dialogs
        ["ConfirmDelete"] = "\u00cates-vous s\u00fbr de vouloir supprimer '{0}' ?",
        ["ConfirmDeleteDataSource"] = "Voulez-vous vraiment supprimer la source de donn\u00e9es '{0}' ?",
        ["ConfirmDeleteGroup"] = "Voulez-vous vraiment supprimer le groupe '{0}' ?\n\nLes sources de donn\u00e9es de ce groupe ne seront pas supprim\u00e9es.",

        // === Connector: FileSystem ===
        ["Connector_FileSystem_Name"] = "Syst\u00e8me de Fichiers",
        ["Connector_FileSystem_Description"] = "Recherche les fichiers et dossiers dans le syst\u00e8me de fichiers local.",
        ["Connector_FileSystem_BasePath"] = "Chemin de Base",
        ["Connector_FileSystem_BasePath_Desc"] = "Le chemin du dossier \u00e0 rechercher.",
        ["Connector_FileSystem_SearchPattern"] = "Mod\u00e8le de Recherche",
        ["Connector_FileSystem_SearchPattern_Desc"] = "Mod\u00e8le de fichier (ex. *.txt, *.pdf)",
        ["Connector_FileSystem_IncludeSubdirs"] = "Inclure les Sous-dossiers",
        ["Connector_FileSystem_IncludeSubdirs_Desc"] = "Indique si les sous-dossiers doivent \u00eatre recherch\u00e9s.",
        ["Connector_FileSystem_Open"] = "Ouvrir",
        ["Connector_FileSystem_Open_Desc"] = "Ouvrir le fichier avec le programme par d\u00e9faut",
        ["Connector_FileSystem_OpenFolder"] = "Ouvrir le Dossier",
        ["Connector_FileSystem_OpenFolder_Desc"] = "Ouvrir le dossier parent",
        ["Connector_FileSystem_CopyPath"] = "Copier le Chemin",
        ["Connector_FileSystem_CopyPath_Desc"] = "Copier le chemin du fichier dans le presse-papiers",
        ["Connector_FileSystem_Path"] = "Chemin",
        ["Connector_FileSystem_Size"] = "Taille",
        ["Connector_FileSystem_Created"] = "Cr\u00e9\u00e9",
        ["Connector_FileSystem_Modified"] = "Modifi\u00e9",
        ["Connector_FileSystem_Type"] = "Type",

        // === Connector: DuckDuckGo ===
        ["Connector_DuckDuckGo_Name"] = "Recherche Web DuckDuckGo",
        ["Connector_DuckDuckGo_Description"] = "Effectue des recherches web via DuckDuckGo.",
        ["Connector_DuckDuckGo_MaxResults"] = "R\u00e9sultats Maximum",
        ["Connector_DuckDuckGo_MaxResults_Desc"] = "Nombre de r\u00e9sultats de recherche \u00e0 retourner (1-30).",
        ["Connector_DuckDuckGo_Region"] = "R\u00e9gion",
        ["Connector_DuckDuckGo_Region_Desc"] = "Param\u00e8tre r\u00e9gional pour les r\u00e9sultats (ex. 'fr-fr' pour France, 'wt-wt' pour mondial).",
        ["Connector_DuckDuckGo_SafeSearch"] = "Recherche S\u00e9curis\u00e9e",
        ["Connector_DuckDuckGo_SafeSearch_Desc"] = "Active le filtre de recherche s\u00e9curis\u00e9e pour des r\u00e9sultats familiaux.",
        ["Connector_DuckDuckGo_OpenBrowser"] = "Ouvrir dans le Navigateur",
        ["Connector_DuckDuckGo_OpenBrowser_Desc"] = "Ouvrir la page web dans le navigateur par d\u00e9faut",
        ["Connector_DuckDuckGo_CopyUrl"] = "Copier l'URL",
        ["Connector_DuckDuckGo_CopyUrl_Desc"] = "Copier l'URL dans le presse-papiers",
        ["Connector_DuckDuckGo_SearchMore"] = "Rechercher sur DuckDuckGo",
        ["Connector_DuckDuckGo_SearchMore_Desc"] = "Afficher plus de r\u00e9sultats sur DuckDuckGo",
        ["Connector_DuckDuckGo_WebResult"] = "R\u00e9sultat de Recherche Web",
        ["Connector_DuckDuckGo_Position"] = "Position",

        // === Connector: Microsoft 365 ===
        ["Connector_M365_Name"] = "Microsoft 365",
        ["Connector_M365_Description"] = "Recherche dans Microsoft 365 : Calendrier, ToDo, Emails et OneNote.",
        ["Connector_M365_ClientId"] = "ID Client (App-ID)",
        ["Connector_M365_ClientId_Desc"] = "L'ID d'application (Client) de l'enregistrement d'application Azure.",
        ["Connector_M365_TenantId"] = "ID du Tenant",
        ["Connector_M365_TenantId_Desc"] = "L'ID du Tenant (ou 'common' pour multi-tenant, 'consumers' pour comptes personnels).",
        ["Connector_M365_SearchCalendar"] = "Rechercher Calendrier",
        ["Connector_M365_SearchCalendar_Desc"] = "Inclure les \u00e9v\u00e9nements du calendrier dans la recherche.",
        ["Connector_M365_SearchToDo"] = "Rechercher ToDo",
        ["Connector_M365_SearchToDo_Desc"] = "Inclure les t\u00e2ches Microsoft ToDo dans la recherche.",
        ["Connector_M365_SearchMail"] = "Rechercher Emails",
        ["Connector_M365_SearchMail_Desc"] = "Inclure les emails dans la recherche.",
        ["Connector_M365_SearchOneNote"] = "Rechercher OneNote",
        ["Connector_M365_SearchOneNote_Desc"] = "Inclure les pages OneNote dans la recherche.",
        ["Connector_M365_MaxDaysBack"] = "Jours Maximum en Arri\u00e8re",
        ["Connector_M365_MaxDaysBack_Desc"] = "Combien de jours en arri\u00e8re pour rechercher les \u00e9v\u00e9nements et emails.",
        ["Connector_M365_OpenOutlook"] = "Ouvrir dans Outlook",
        ["Connector_M365_OpenOutlook_Desc"] = "Ouvrir dans Outlook Web",
        ["Connector_M365_OpenToDo"] = "Ouvrir dans ToDo",
        ["Connector_M365_OpenToDo_Desc"] = "Ouvrir la t\u00eache dans Microsoft ToDo",
        ["Connector_M365_OpenOneNote"] = "Ouvrir dans OneNote",
        ["Connector_M365_OpenOneNote_Desc"] = "Ouvrir la page dans OneNote",
        ["Connector_M365_CopyLink"] = "Copier le Lien",
        ["Connector_M365_CopyLink_Desc"] = "Copier le lien dans le presse-papiers",
        ["Connector_M365_OpenBrowser"] = "Ouvrir dans le Navigateur",
        ["Connector_M365_OpenBrowser_Desc"] = "Ouvrir dans le navigateur par d\u00e9faut",
        ["Connector_M365_CalendarEntry"] = "Entr\u00e9e de Calendrier",
        ["Connector_M365_Task"] = "T\u00e2che",
        ["Connector_M365_Email"] = "Email",
        ["Connector_M365_OneNotePage"] = "Page OneNote",
        ["Connector_M365_Subject"] = "Sujet",
        ["Connector_M365_Start"] = "D\u00e9but",
        ["Connector_M365_End"] = "Fin",
        ["Connector_M365_Location"] = "Lieu",
        ["Connector_M365_Organizer"] = "Organisateur",
        ["Connector_M365_List"] = "Liste",
        ["Connector_M365_Status"] = "Statut",
        ["Connector_M365_Priority"] = "Priorit\u00e9",
        ["Connector_M365_DueDate"] = "Date d'\u00c9ch\u00e9ance",
        ["Connector_M365_Notes"] = "Notes",
        ["Connector_M365_From"] = "De",
        ["Connector_M365_Received"] = "Re\u00e7u",
        ["Connector_M365_Attachments"] = "Pi\u00e8ces Jointes",
        ["Connector_M365_Preview"] = "Aper\u00e7u",
        ["Connector_M365_Title"] = "Titre",
        ["Connector_M365_Section"] = "Section",

        // === Connector: SQL Database ===
        ["Connector_SQL_Name"] = "Base de Donn\u00e9es SQL",
        ["Connector_SQL_Description"] = "Recherche dans les bases de donn\u00e9es SQL (MySQL, MSSQL, PostgreSQL).",
        ["Connector_SQL_ConnectionString"] = "Cha\u00eene de Connexion",
        ["Connector_SQL_ConnectionString_Desc"] = "Cha\u00eene de connexion \u00e0 la base de donn\u00e9es (ex. 'Server=localhost;Database=mydb;User Id=user;Password=pass;')",
        ["Connector_SQL_DatabaseType"] = "Type de Base de Donn\u00e9es",
        ["Connector_SQL_DatabaseType_Desc"] = "Type de base de donn\u00e9es : MSSQL, MySQL ou PostgreSQL",
        ["Connector_SQL_Tables"] = "Tables",
        ["Connector_SQL_Tables_Desc"] = "Liste de tables s\u00e9par\u00e9es par des virgules, ou '*' pour toutes. Ignor\u00e9 si une requ\u00eate personnalis\u00e9e est fournie.",
        ["Connector_SQL_CustomQuery"] = "Requ\u00eate SQL Personnalis\u00e9e",
        ["Connector_SQL_CustomQuery_Desc"] = "Optionnel : Instruction SELECT personnalis\u00e9e. Utilisez @SearchTerm comme marqueur pour le terme de recherche.",
        ["Connector_SQL_CopyJson"] = "Copier en JSON",
        ["Connector_SQL_CopyJson_Desc"] = "Copier l'enregistrement en JSON dans le presse-papiers",
        ["Connector_SQL_CopyInsert"] = "Copier en INSERT",
        ["Connector_SQL_CopyInsert_Desc"] = "Copier comme instruction SQL INSERT",
        ["Connector_SQL_MatchesIn"] = "Correspondances dans",
        ["Connector_SQL_Record"] = "Enregistrement",

        // === Connector: OpenAI ===
        ["OpenAiConnectorName"] = "API OpenAI",
        ["OpenAiConnectorDescription"] = "Interroge les APIs IA compatibles OpenAI (ChatGPT, LLMs locaux, etc.).",
        ["OpenAiApiEndpoint"] = "Point de Terminaison API",
        ["OpenAiApiEndpointDesc"] = "L'URL du point de terminaison API (ex. https://api.openai.com/v1/chat/completions)",
        ["OpenAiApiKey"] = "Cl\u00e9 API",
        ["OpenAiApiKeyDesc"] = "Votre jeton d'authentification API.",
        ["OpenAiModel"] = "Mod\u00e8le",
        ["OpenAiModelDesc"] = "Le mod\u00e8le IA \u00e0 utiliser (ex. gpt-3.5-turbo, gpt-4, llama2).",
        ["OpenAiSystemPrompt"] = "Prompt Syst\u00e8me",
        ["OpenAiSystemPromptDesc"] = "Prompt syst\u00e8me optionnel pour d\u00e9finir le comportement de l'IA.",
        ["OpenAiMaxTokens"] = "Tokens Maximum",
        ["OpenAiMaxTokensDesc"] = "Nombre maximum de tokens dans la r\u00e9ponse (1-128000).",
        ["OpenAiTemperature"] = "Temp\u00e9rature",
        ["OpenAiTemperatureDesc"] = "Cr\u00e9ativit\u00e9 des r\u00e9ponses (0.0 = d\u00e9terministe, 2.0 = tr\u00e8s cr\u00e9atif).",
        ["OpenAiResponse"] = "R\u00e9ponse IA",
        ["OpenAiError"] = "Erreur API",
        ["OpenAiErrorDesc"] = "Erreur lors de la requ\u00eate API",
        ["OpenAiMetaModel"] = "Mod\u00e8le",
        ["OpenAiMetaPromptTokens"] = "Tokens de Prompt",
        ["OpenAiMetaCompletionTokens"] = "Tokens de R\u00e9ponse",
        ["OpenAiMetaTotalTokens"] = "Tokens Totaux",
        ["OpenAiMetaFinishReason"] = "Raison de Fin",
        ["OpenAiMetaQuery"] = "Requ\u00eate",
        ["OpenAiActionCopyResponse"] = "Copier la R\u00e9ponse",
        ["OpenAiActionCopyResponseDesc"] = "Copier la r\u00e9ponse IA dans le presse-papiers",
        ["OpenAiActionCopyQuery"] = "Copier la Requ\u00eate",
        ["OpenAiActionCopyQueryDesc"] = "Copier la requ\u00eate originale dans le presse-papiers",

        // === Connector: Generic API ===
        ["GenericApiConnectorName"] = "API G\u00e9n\u00e9rique",
        ["GenericApiConnectorDescription"] = "Se connecte \u00e0 n'importe quelle API REST avec authentification flexible et placement des param\u00e8tres de recherche.",
        ["GenericApiEndpoint"] = "Point de Terminaison API",
        ["GenericApiEndpointDesc"] = "L'URL de base de l'API. Utilisez [SEARCH] comme marqueur pour le terme de recherche.",
        ["GenericApiHttpMethod"] = "M\u00e9thode HTTP",
        ["GenericApiHttpMethodDesc"] = "M\u00e9thode HTTP \u00e0 utiliser : GET, POST, PUT, PATCH, DELETE",
        ["GenericApiAuthType"] = "Type d'Authentification",
        ["GenericApiAuthTypeDesc"] = "M\u00e9thode d'authentification : None, Header, Bearer, OAuth2, JWT, Query, Post",
        ["GenericApiAuthHeaderName"] = "Nom de l'En-t\u00eate Auth",
        ["GenericApiAuthHeaderNameDesc"] = "Nom de l'en-t\u00eate d'authentification (ex. Authorization, X-API-Key)",
        ["GenericApiAuthHeaderValue"] = "Valeur de l'En-t\u00eate Auth",
        ["GenericApiAuthHeaderValueDesc"] = "Valeur pour l'en-t\u00eate d'authentification",
        ["GenericApiAuthToken"] = "Token d'Auth",
        ["GenericApiAuthTokenDesc"] = "Token d'authentification pour Bearer/JWT, ou key=value pour l'auth par param\u00e8tre Query/Post",
        ["GenericApiOAuth2TokenEndpoint"] = "Point de Terminaison Token OAuth2",
        ["GenericApiOAuth2TokenEndpointDesc"] = "URL pour obtenir le token d'acc\u00e8s OAuth2",
        ["GenericApiOAuth2ClientId"] = "Client ID OAuth2",
        ["GenericApiOAuth2ClientIdDesc"] = "ID client pour l'authentification OAuth2",
        ["GenericApiOAuth2ClientSecret"] = "Client Secret OAuth2",
        ["GenericApiOAuth2ClientSecretDesc"] = "Secret client pour l'authentification OAuth2",
        ["GenericApiOAuth2Scope"] = "Scope OAuth2",
        ["GenericApiOAuth2ScopeDesc"] = "Scope OAuth2 (optionnel)",
        ["GenericApiQueryParameters"] = "Param\u00e8tres de Query",
        ["GenericApiQueryParametersDesc"] = "Param\u00e8tres de query URL. Utilisez [SEARCH] pour le terme de recherche (ex. q=[SEARCH]&limit=10)",
        ["GenericApiPostBody"] = "Corps POST",
        ["GenericApiPostBodyDesc"] = "Corps de la requ\u00eate pour POST/PUT/PATCH. Utilisez [SEARCH] pour le terme de recherche.",
        ["GenericApiContentType"] = "Type de Contenu",
        ["GenericApiContentTypeDesc"] = "En-t\u00eate Content-Type pour le corps de la requ\u00eate (ex. application/json)",
        ["GenericApiCustomHeaders"] = "En-t\u00eates Personnalis\u00e9s",
        ["GenericApiCustomHeadersDesc"] = "En-t\u00eates suppl\u00e9mentaires, un par ligne (format : Nom-En-t\u00eate: valeur)",
        ["GenericApiResultJsonPath"] = "Chemin JSON du R\u00e9sultat",
        ["GenericApiResultJsonPathDesc"] = "Chemin JSON vers le tableau de r\u00e9sultats (ex. data.results)",
        ["GenericApiResultTitleProperty"] = "Propri\u00e9t\u00e9 du Titre",
        ["GenericApiResultTitlePropertyDesc"] = "Nom de la propri\u00e9t\u00e9 JSON pour le titre du r\u00e9sultat",
        ["GenericApiResultDescriptionProperty"] = "Propri\u00e9t\u00e9 de la Description",
        ["GenericApiResultDescriptionPropertyDesc"] = "Nom de la propri\u00e9t\u00e9 JSON pour la description du r\u00e9sultat",
        ["GenericApiResultUrlProperty"] = "Propri\u00e9t\u00e9 de l'URL",
        ["GenericApiResultUrlPropertyDesc"] = "Nom de la propri\u00e9t\u00e9 JSON pour l'URL du r\u00e9sultat",
        ["GenericApiTimeout"] = "Timeout (secondes)",
        ["GenericApiTimeoutDesc"] = "Timeout de la requ\u00eate en secondes (1-300)",
        ["GenericApiError"] = "Erreur API",
        ["GenericApiRawResponse"] = "R\u00e9ponse Brute",
        ["GenericApiMetaQuery"] = "Requ\u00eate",
        ["GenericApiActionOpenUrl"] = "Ouvrir l'URL",
        ["GenericApiActionOpenUrlDesc"] = "Ouvrir l'URL du r\u00e9sultat dans le navigateur",
        ["GenericApiActionCopyJson"] = "Copier en JSON",
        ["GenericApiActionCopyJsonDesc"] = "Copier les donn\u00e9es du r\u00e9sultat en JSON",
        ["GenericApiActionCopyUrl"] = "Copier l'URL",
        ["GenericApiActionCopyUrlDesc"] = "Copier l'URL dans le presse-papiers",

        // === Connector: IMAP ===
        ["ImapConnectorName"] = "Email IMAP",
        ["ImapConnectorDescription"] = "Recherche des emails via le protocole IMAP. Prend en charge OAuth2 et l'authentification par mot de passe.",
        ["ImapServer"] = "Serveur IMAP",
        ["ImapServerDesc"] = "Nom d'h\u00f4te du serveur IMAP (ex. imap.gmail.com, outlook.office365.com)",
        ["ImapPort"] = "Port",
        ["ImapPortDesc"] = "Port du serveur IMAP (g\u00e9n\u00e9ralement 993 pour SSL/TLS, 143 pour STARTTLS)",
        ["ImapEmailAddress"] = "Adresse Email",
        ["ImapEmailAddressDesc"] = "Votre adresse email pour l'authentification",
        ["ImapAuthType"] = "Type d'Authentification",
        ["ImapAuthTypeDesc"] = "M\u00e9thode d'authentification : Password ou OAuth2",
        ["ImapPassword"] = "Mot de Passe",
        ["ImapPasswordDesc"] = "Mot de passe ou mot de passe sp\u00e9cifique \u00e0 l'application pour l'authentification",
        ["ImapOAuth2Token"] = "Token d'Acc\u00e8s OAuth2",
        ["ImapOAuth2TokenDesc"] = "Token d'acc\u00e8s OAuth2 pour l'authentification (requis si le type d'auth est OAuth2)",
        ["ImapEncryption"] = "Chiffrement",
        ["ImapEncryptionDesc"] = "M\u00e9thode de chiffrement : SslTls (recommand\u00e9), StartTls ou None",
        ["ImapFolderName"] = "Dossier",
        ["ImapFolderNameDesc"] = "Dossier de messagerie \u00e0 rechercher (ex. INBOX, Sent, Archive)",
        ["ImapMaxResults"] = "R\u00e9sultats Maximum",
        ["ImapMaxResultsDesc"] = "Nombre maximum d'emails \u00e0 retourner (1-500)",
        ["ImapMaxDaysBack"] = "Jours Maximum en Arri\u00e8re",
        ["ImapMaxDaysBackDesc"] = "Combien de jours en arri\u00e8re pour rechercher les emails (1-365)",
        ["ImapNoSubject"] = "(Sans Sujet)",
        ["ImapError"] = "Erreur IMAP",
        ["ImapErrorDesc"] = "Erreur de connexion au serveur IMAP",
        ["ImapMetaFrom"] = "De",
        ["ImapMetaFromEmail"] = "De (Email)",
        ["ImapMetaSubject"] = "Sujet",
        ["ImapMetaDate"] = "Date",
        ["ImapMetaHasAttachments"] = "Pi\u00e8ces Jointes",
        ["ImapMetaFolder"] = "Dossier",
        ["ImapActionCopyBody"] = "Copier le Corps",
        ["ImapActionCopyBodyDesc"] = "Copier le corps de l'email dans le presse-papiers",
        ["ImapActionCopySender"] = "Copier l'Exp\u00e9diteur",
        ["ImapActionCopySenderDesc"] = "Copier l'adresse email de l'exp\u00e9diteur dans le presse-papiers",

        // === Connector: Find In Files ===
        ["Connector_FindInFiles_Name"] = "Rechercher dans les Fichiers",
        ["Connector_FindInFiles_Description"] = "Recherche du contenu texte dans les fichiers. Prend en charge le texte brut et les expressions r\u00e9guli\u00e8res.",
        ["Connector_FindInFiles_BasePath"] = "Chemin de Base",
        ["Connector_FindInFiles_BasePath_Desc"] = "Le chemin du dossier dans lequel rechercher.",
        ["Connector_FindInFiles_FilePattern"] = "Mod\u00e8le de Fichier",
        ["Connector_FindInFiles_FilePattern_Desc"] = "Mod\u00e8le de fichier \u00e0 faire correspondre (ex. *.txt, *.cs, *.*).",
        ["Connector_FindInFiles_IncludeSubdirs"] = "Inclure les Sous-dossiers",
        ["Connector_FindInFiles_IncludeSubdirs_Desc"] = "Indique si les sous-dossiers doivent \u00eatre recherch\u00e9s.",
        ["Connector_FindInFiles_UseRegex"] = "Utiliser une Expression R\u00e9guli\u00e8re",
        ["Connector_FindInFiles_UseRegex_Desc"] = "Activer pour utiliser des expressions r\u00e9guli\u00e8res au lieu du texte brut.",
        ["Connector_FindInFiles_CaseSensitive"] = "Respecter la Casse",
        ["Connector_FindInFiles_CaseSensitive_Desc"] = "Activer pour une correspondance sensible \u00e0 la casse.",
        ["Connector_FindInFiles_MatchesFound"] = "correspondances trouv\u00e9es",
        ["Connector_FindInFiles_Path"] = "Chemin",
        ["Connector_FindInFiles_Directory"] = "R\u00e9pertoire",
        ["Connector_FindInFiles_FileName"] = "Nom de Fichier",
        ["Connector_FindInFiles_Size"] = "Taille",
        ["Connector_FindInFiles_Modified"] = "Modifi\u00e9",
        ["Connector_FindInFiles_MatchCount"] = "Nombre de Correspondances",
        ["Connector_FindInFiles_Matches"] = "Correspondances",
        ["Connector_FindInFiles_SearchTerm"] = "Terme de Recherche",
        ["Connector_FindInFiles_Line"] = "Ligne",
        ["Connector_FindInFiles_Column"] = "Colonne",
        ["Connector_FindInFiles_FileInfo"] = "Informations du Fichier",
        ["Connector_FindInFiles_MatchesHeader"] = "Correspondances",
        ["Connector_FindInFiles_AndMore"] = "et",
        ["Connector_FindInFiles_MoreMatches"] = "correspondances suppl\u00e9mentaires",
        ["Connector_FindInFiles_Open"] = "Ouvrir",
        ["Connector_FindInFiles_Open_Desc"] = "Ouvrir le fichier avec le programme par d\u00e9faut",
        ["Connector_FindInFiles_OpenFolder"] = "Ouvrir le Dossier",
        ["Connector_FindInFiles_OpenFolder_Desc"] = "Ouvrir le dossier contenant dans l'Explorateur",
        ["Connector_FindInFiles_CopyPath"] = "Copier le Chemin",
        ["Connector_FindInFiles_CopyPath_Desc"] = "Copier le chemin du fichier dans le presse-papiers",
        ["Connector_FindInFiles_CopyMatches"] = "Copier les Correspondances",
        ["Connector_FindInFiles_CopyMatches_Desc"] = "Copier toutes les correspondances dans le presse-papiers",

        // === AI Search ===
        ["AiSearch"] = "Recherche IA",
        ["AiSearchTooltip"] = "Analyser les r\u00e9sultats avec l'IA",
        ["AiSearchDescription"] = "Entrez un prompt syst\u00e8me pour analyser les r\u00e9sultats de recherche avec l'IA.",
        ["AiSystemPrompt"] = "Prompt Syst\u00e8me",
        ["AiDefaultPrompt"] = "Vous \u00eates un assistant utile. Analysez les r\u00e9sultats de recherche suivants et fournissez un r\u00e9sum\u00e9 concis mettant en \u00e9vidence les informations les plus pertinentes.",
        ["AiResultsToAnalyze"] = "{0} r\u00e9sultats seront analys\u00e9s",
        ["AiAnalyzeButton"] = "Analyser avec l'IA",
        ["AiPromptRequired"] = "Veuillez entrer un prompt syst\u00e8me.",
        ["AiNoResults"] = "Aucun r\u00e9sultat \u00e0 analyser. Veuillez d'abord effectuer une recherche.",
        ["AiAnalyzing"] = "Analyse avec l'IA...",
        ["AiAnalysisComplete"] = "Analyse IA termin\u00e9e",
        ["AiAnalysisResult"] = "R\u00e9sultat de l'Analyse IA",
        ["AiCopyResponse"] = "Copier la R\u00e9ponse",
        ["AiResponseCopied"] = "R\u00e9ponse copi\u00e9e dans le presse-papiers.",
        ["AiModel"] = "Mod\u00e8le",
        ["AiPromptTokens"] = "Prompt",
        ["AiCompletionTokens"] = "R\u00e9ponse",
        ["AiTotalTokens"] = "Total",
        ["AiApiEndpoint"] = "Point de Terminaison API",
        ["AiApiKey"] = "Cl\u00e9 API",
        ["AiModelHint"] = "ex. gpt-4, gpt-3.5-turbo, llama2",
    };
}
