// Meta Search and Control Center (c) 2026 Dennis Michael Heine
namespace MSCC.Localization;

/// <summary>
/// Traduzioni italiane.
/// </summary>
public static class Strings_it
{
    public static Dictionary<string, string> Resources { get; } = new()
    {
        // Application
        ["AppTitle"] = "MSCC - Centro Comandi Meta Ricerca",
        ["Ready"] = "Pronto",
        ["Error"] = "Errore",
        ["Warning"] = "Avviso",
        ["Success"] = "Successo",
        ["Cancel"] = "Annulla",
        ["Save"] = "Salva",
        ["Delete"] = "Elimina",
        ["Edit"] = "Modifica",
        ["Add"] = "Aggiungi",
        ["Close"] = "Chiudi",
        ["Yes"] = "S\u00ec",
        ["No"] = "No",
        ["OK"] = "OK",

        // Menu
        ["MenuFile"] = "File",
        ["MenuExit"] = "Esci",
        ["MenuPlugins"] = "Plugin",
        ["MenuScriptManager"] = "Gestore Script...",
        ["MenuReloadScripts"] = "Ricarica Script",
        ["MenuSettings"] = "Impostazioni...",
        ["MenuHelp"] = "Aiuto",
        ["MenuAbout"] = "Informazioni su MSCC",

        // Search
        ["Search"] = "Cerca",
        ["SearchResults"] = "Risultati della Ricerca",
        ["Searching"] = "Ricerca in corso...",
        ["SearchCompleted"] = "Ricerca completata",
        ["NoResults"] = "Nessun risultato trovato",
        ["ResultsFound"] = "{0} risultati trovati",
        ["Source"] = "Fonte",

        // DataSources
        ["DataSources"] = "Origini Dati",
        ["NewDataSource"] = "Nuova Origine Dati",
        ["EditDataSource"] = "Modifica Origine Dati",
        ["DeleteDataSource"] = "Elimina Origine Dati",
        ["DataSourceName"] = "Nome",
        ["ConnectorType"] = "Tipo di Connettore",
        ["Configuration"] = "Configurazione",
        ["Enabled"] = "Abilitato",
        ["NoDataSourcesSelected"] = "Nessuna origine dati selezionata o disponibile",

        // Groups
        ["Groups"] = "Gruppi",
        ["NewGroup"] = "Nuovo Gruppo",
        ["EditGroup"] = "Modifica Gruppo",
        ["DeleteGroup"] = "Elimina Gruppo",
        ["GroupName"] = "Nome",
        ["GroupColor"] = "Colore",
        ["NoGroup"] = "(Nessun Gruppo)",

        // Details
        ["DetailView"] = "Vista Dettagliata",
        ["SelectResultForDetails"] = "Seleziona un risultato per visualizzare i dettagli.",
        ["Open"] = "Apri",
        ["OpenFolder"] = "Apri Cartella",
        ["CopyPath"] = "Copia Percorso",

        // Labels
        ["AddLabel"] = "Aggiungi Etichetta",
        ["SelectResultFirst"] = "Seleziona prima un risultato",
        ["KeywordSearch"] = "Ricerca per Parola Chiave",
        ["SearchByKeyword"] = "Cerca per Parola Chiave",
        ["CurrentQuery"] = "Query Attuale",
        ["SavedQueries"] = "Query Salvate",
        ["Load"] = "Carica",
        ["Labels"] = "Etichette",

        // Script Editor
        ["ScriptEditor"] = "Editor di Script",
        ["ScriptManager"] = "Gestore Script",
        ["NewScript"] = "Nuovo Script",
        ["Compile"] = "Compila",
        ["Validate"] = "Valida",
        ["Insert"] = "Inserisci",
        ["Errors"] = "Errori",
        ["Warnings"] = "Avvisi",
        ["Line"] = "Riga",
        ["Column"] = "Colonna",
        ["CompileSuccess"] = "Compilazione riuscita - Connettore registrato",
        ["CompileFailed"] = "Compilazione fallita - {0} errori",

        // Settings
        ["Settings"] = "Impostazioni",
        ["Language"] = "Lingua",
        ["SelectLanguage"] = "Seleziona Lingua",
        ["RestartRequired"] = "Alcune modifiche richiedono il riavvio.",
        ["General"] = "Generale",
        ["Appearance"] = "Aspetto",

        // Validation
        ["FieldRequired"] = "Il campo '{0}' \u00e8 obbligatorio.",
        ["InvalidValue"] = "Valore non valido",
        ["ValidationError"] = "Errore di Validazione",

        // Status
        ["Loading"] = "Caricamento...",
        ["Saving"] = "Salvataggio...",
        ["Compiling"] = "Compilazione...",
        ["ScriptConnectorsLoaded"] = "{0} connettori script caricati",
        ["DataSourceCreated"] = "Origine dati '{0}' creata",
        ["DataSourceUpdated"] = "Origine dati '{0}' aggiornata",
        ["DataSourceDeleted"] = "Origine dati '{0}' eliminata",
        ["GroupCreated"] = "Gruppo '{0}' creato",
        ["GroupUpdated"] = "Gruppo '{0}' aggiornato",
        ["GroupDeleted"] = "Gruppo '{0}' eliminato",

        // Confirmation dialogs
        ["ConfirmDelete"] = "Sei sicuro di voler eliminare '{0}'?",
        ["ConfirmDeleteDataSource"] = "Vuoi davvero eliminare l'origine dati '{0}'?",
        ["ConfirmDeleteGroup"] = "Vuoi davvero eliminare il gruppo '{0}'?\n\nLe origini dati in questo gruppo non verranno eliminate.",

        // === Connector: FileSystem ===
        ["Connector_FileSystem_Name"] = "File System",
        ["Connector_FileSystem_Description"] = "Cerca file e cartelle nel file system locale.",
        ["Connector_FileSystem_BasePath"] = "Percorso Base",
        ["Connector_FileSystem_BasePath_Desc"] = "Il percorso della cartella da cercare.",
        ["Connector_FileSystem_SearchPattern"] = "Modello di Ricerca",
        ["Connector_FileSystem_SearchPattern_Desc"] = "Modello di file (es. *.txt, *.pdf)",
        ["Connector_FileSystem_IncludeSubdirs"] = "Includi Sottocartelle",
        ["Connector_FileSystem_IncludeSubdirs_Desc"] = "Specifica se cercare nelle sottocartelle.",
        ["Connector_FileSystem_Open"] = "Apri",
        ["Connector_FileSystem_Open_Desc"] = "Apri file con programma predefinito",
        ["Connector_FileSystem_OpenFolder"] = "Apri Cartella",
        ["Connector_FileSystem_OpenFolder_Desc"] = "Apri cartella contenitore",
        ["Connector_FileSystem_CopyPath"] = "Copia Percorso",
        ["Connector_FileSystem_CopyPath_Desc"] = "Copia percorso file negli appunti",
        ["Connector_FileSystem_Path"] = "Percorso",
        ["Connector_FileSystem_Size"] = "Dimensione",
        ["Connector_FileSystem_Created"] = "Creato",
        ["Connector_FileSystem_Modified"] = "Modificato",
        ["Connector_FileSystem_Type"] = "Tipo",

        // === Connector: DuckDuckGo ===
        ["Connector_DuckDuckGo_Name"] = "Ricerca Web DuckDuckGo",
        ["Connector_DuckDuckGo_Description"] = "Esegue ricerche web tramite DuckDuckGo.",
        ["Connector_DuckDuckGo_MaxResults"] = "Risultati Massimi",
        ["Connector_DuckDuckGo_MaxResults_Desc"] = "Numero di risultati di ricerca da restituire (1-30).",
        ["Connector_DuckDuckGo_Region"] = "Regione",
        ["Connector_DuckDuckGo_Region_Desc"] = "Impostazione regionale per i risultati (es. 'it-it' per Italia, 'wt-wt' per mondiale).",
        ["Connector_DuckDuckGo_SafeSearch"] = "Ricerca Sicura",
        ["Connector_DuckDuckGo_SafeSearch_Desc"] = "Attiva il filtro di ricerca sicura per risultati adatti alle famiglie.",
        ["Connector_DuckDuckGo_OpenBrowser"] = "Apri nel Browser",
        ["Connector_DuckDuckGo_OpenBrowser_Desc"] = "Apri pagina web nel browser predefinito",
        ["Connector_DuckDuckGo_CopyUrl"] = "Copia URL",
        ["Connector_DuckDuckGo_CopyUrl_Desc"] = "Copia URL negli appunti",
        ["Connector_DuckDuckGo_SearchMore"] = "Cerca su DuckDuckGo",
        ["Connector_DuckDuckGo_SearchMore_Desc"] = "Mostra pi\u00f9 risultati su DuckDuckGo",
        ["Connector_DuckDuckGo_WebResult"] = "Risultato Ricerca Web",
        ["Connector_DuckDuckGo_Position"] = "Posizione",

        // === Connector: Microsoft 365 ===
        ["Connector_M365_Name"] = "Microsoft 365",
        ["Connector_M365_Description"] = "Cerca in Microsoft 365: Calendario, ToDo, Email e OneNote.",
        ["Connector_M365_ClientId"] = "ID Client (App-ID)",
        ["Connector_M365_ClientId_Desc"] = "L'ID dell'applicazione (Client) dalla registrazione dell'app Azure.",
        ["Connector_M365_TenantId"] = "ID Tenant",
        ["Connector_M365_TenantId_Desc"] = "L'ID del Tenant (o 'common' per multi-tenant, 'consumers' per account personali).",
        ["Connector_M365_SearchCalendar"] = "Cerca Calendario",
        ["Connector_M365_SearchCalendar_Desc"] = "Includi eventi del calendario nella ricerca.",
        ["Connector_M365_SearchToDo"] = "Cerca ToDo",
        ["Connector_M365_SearchToDo_Desc"] = "Includi attivit\u00e0 Microsoft ToDo nella ricerca.",
        ["Connector_M365_SearchMail"] = "Cerca Email",
        ["Connector_M365_SearchMail_Desc"] = "Includi email nella ricerca.",
        ["Connector_M365_SearchOneNote"] = "Cerca OneNote",
        ["Connector_M365_SearchOneNote_Desc"] = "Includi pagine OneNote nella ricerca.",
        ["Connector_M365_MaxDaysBack"] = "Giorni Massimi Indietro",
        ["Connector_M365_MaxDaysBack_Desc"] = "Quanti giorni indietro cercare eventi del calendario ed email.",
        ["Connector_M365_OpenOutlook"] = "Apri in Outlook",
        ["Connector_M365_OpenOutlook_Desc"] = "Apri in Outlook Web",
        ["Connector_M365_OpenToDo"] = "Apri in ToDo",
        ["Connector_M365_OpenToDo_Desc"] = "Apri attivit\u00e0 in Microsoft ToDo",
        ["Connector_M365_OpenOneNote"] = "Apri in OneNote",
        ["Connector_M365_OpenOneNote_Desc"] = "Apri pagina in OneNote",
        ["Connector_M365_CopyLink"] = "Copia Link",
        ["Connector_M365_CopyLink_Desc"] = "Copia link negli appunti",
        ["Connector_M365_OpenBrowser"] = "Apri nel Browser",
        ["Connector_M365_OpenBrowser_Desc"] = "Apri nel browser predefinito",
        ["Connector_M365_CalendarEntry"] = "Voce Calendario",
        ["Connector_M365_Task"] = "Attivit\u00e0",
        ["Connector_M365_Email"] = "Email",
        ["Connector_M365_OneNotePage"] = "Pagina OneNote",
        ["Connector_M365_Subject"] = "Oggetto",
        ["Connector_M365_Start"] = "Inizio",
        ["Connector_M365_End"] = "Fine",
        ["Connector_M365_Location"] = "Luogo",
        ["Connector_M365_Organizer"] = "Organizzatore",
        ["Connector_M365_List"] = "Lista",
        ["Connector_M365_Status"] = "Stato",
        ["Connector_M365_Priority"] = "Priorit\u00e0",
        ["Connector_M365_DueDate"] = "Data di Scadenza",
        ["Connector_M365_Notes"] = "Note",
        ["Connector_M365_From"] = "Da",
        ["Connector_M365_Received"] = "Ricevuto",
        ["Connector_M365_Attachments"] = "Allegati",
        ["Connector_M365_Preview"] = "Anteprima",
        ["Connector_M365_Title"] = "Titolo",
        ["Connector_M365_Section"] = "Sezione",

        // === Connector: SQL Database ===
        ["Connector_SQL_Name"] = "Database SQL",
        ["Connector_SQL_Description"] = "Cerca in database SQL (MySQL, MSSQL, PostgreSQL).",
        ["Connector_SQL_ConnectionString"] = "Stringa di Connessione",
        ["Connector_SQL_ConnectionString_Desc"] = "Stringa di connessione al database (es. 'Server=localhost;Database=mydb;User Id=user;Password=pass;')",
        ["Connector_SQL_DatabaseType"] = "Tipo di Database",
        ["Connector_SQL_DatabaseType_Desc"] = "Tipo di database: MSSQL, MySQL o PostgreSQL",
        ["Connector_SQL_Tables"] = "Tabelle",
        ["Connector_SQL_Tables_Desc"] = "Elenco di tabelle separate da virgole, o '*' per tutte. Ignorato se viene fornita una query personalizzata.",
        ["Connector_SQL_CustomQuery"] = "Query SQL Personalizzata",
        ["Connector_SQL_CustomQuery_Desc"] = "Opzionale: Istruzione SELECT personalizzata. Usa @SearchTerm come segnaposto per il termine di ricerca.",
        ["Connector_SQL_CopyJson"] = "Copia come JSON",
        ["Connector_SQL_CopyJson_Desc"] = "Copia il record come JSON negli appunti",
        ["Connector_SQL_CopyInsert"] = "Copia come INSERT",
        ["Connector_SQL_CopyInsert_Desc"] = "Copia come istruzione SQL INSERT",
        ["Connector_SQL_MatchesIn"] = "Corrispondenze in",
        ["Connector_SQL_Record"] = "Record",

        // === Connector: OpenAI ===
        ["OpenAiConnectorName"] = "API OpenAI",
        ["OpenAiConnectorDescription"] = "Interroga API IA compatibili con OpenAI (ChatGPT, LLM locali, ecc.).",
        ["OpenAiApiEndpoint"] = "Endpoint API",
        ["OpenAiApiEndpointDesc"] = "L'URL dell'endpoint API (es. https://api.openai.com/v1/chat/completions)",
        ["OpenAiApiKey"] = "Chiave API",
        ["OpenAiApiKeyDesc"] = "Il tuo token di autenticazione API.",
        ["OpenAiModel"] = "Modello",
        ["OpenAiModelDesc"] = "Il modello IA da utilizzare (es. gpt-3.5-turbo, gpt-4, llama2).",
        ["OpenAiSystemPrompt"] = "Prompt di Sistema",
        ["OpenAiSystemPromptDesc"] = "Prompt di sistema opzionale per definire il comportamento dell'IA.",
        ["OpenAiMaxTokens"] = "Token Massimi",
        ["OpenAiMaxTokensDesc"] = "Numero massimo di token nella risposta (1-128000).",
        ["OpenAiTemperature"] = "Temperatura",
        ["OpenAiTemperatureDesc"] = "Creativit\u00e0 delle risposte (0.0 = deterministico, 2.0 = molto creativo).",
        ["OpenAiResponse"] = "Risposta IA",
        ["OpenAiError"] = "Errore API",
        ["OpenAiErrorDesc"] = "Errore durante la richiesta API",
        ["OpenAiMetaModel"] = "Modello",
        ["OpenAiMetaPromptTokens"] = "Token di Prompt",
        ["OpenAiMetaCompletionTokens"] = "Token di Risposta",
        ["OpenAiMetaTotalTokens"] = "Token Totali",
        ["OpenAiMetaFinishReason"] = "Motivo di Fine",
        ["OpenAiMetaQuery"] = "Query",
        ["OpenAiActionCopyResponse"] = "Copia Risposta",
        ["OpenAiActionCopyResponseDesc"] = "Copia la risposta IA negli appunti",
        ["OpenAiActionCopyQuery"] = "Copia Query",
        ["OpenAiActionCopyQueryDesc"] = "Copia la query originale negli appunti",

        // === Connector: Generic API ===
        ["GenericApiConnectorName"] = "API Generica",
        ["GenericApiConnectorDescription"] = "Si connette a qualsiasi API REST con autenticazione flessibile e posizionamento dei parametri di ricerca.",
        ["GenericApiEndpoint"] = "Endpoint API",
        ["GenericApiEndpointDesc"] = "L'URL base dell'API. Usa [SEARCH] come segnaposto per il termine di ricerca.",
        ["GenericApiHttpMethod"] = "Metodo HTTP",
        ["GenericApiHttpMethodDesc"] = "Metodo HTTP da utilizzare: GET, POST, PUT, PATCH, DELETE",
        ["GenericApiAuthType"] = "Tipo di Autenticazione",
        ["GenericApiAuthTypeDesc"] = "Metodo di autenticazione: None, Header, Bearer, OAuth2, JWT, Query, Post",
        ["GenericApiAuthHeaderName"] = "Nome Header Auth",
        ["GenericApiAuthHeaderNameDesc"] = "Nome dell'header di autenticazione (es. Authorization, X-API-Key)",
        ["GenericApiAuthHeaderValue"] = "Valore Header Auth",
        ["GenericApiAuthHeaderValueDesc"] = "Valore per l'header di autenticazione",
        ["GenericApiAuthToken"] = "Token Auth",
        ["GenericApiAuthTokenDesc"] = "Token di autenticazione per Bearer/JWT, o key=value per auth parametro Query/Post",
        ["GenericApiOAuth2TokenEndpoint"] = "Endpoint Token OAuth2",
        ["GenericApiOAuth2TokenEndpointDesc"] = "URL per ottenere il token di accesso OAuth2",
        ["GenericApiOAuth2ClientId"] = "Client ID OAuth2",
        ["GenericApiOAuth2ClientIdDesc"] = "ID client per l'autenticazione OAuth2",
        ["GenericApiOAuth2ClientSecret"] = "Client Secret OAuth2",
        ["GenericApiOAuth2ClientSecretDesc"] = "Segreto client per l'autenticazione OAuth2",
        ["GenericApiOAuth2Scope"] = "Scope OAuth2",
        ["GenericApiOAuth2ScopeDesc"] = "Scope OAuth2 (opzionale)",
        ["GenericApiQueryParameters"] = "Parametri Query",
        ["GenericApiQueryParametersDesc"] = "Parametri query URL. Usa [SEARCH] per il termine di ricerca (es. q=[SEARCH]&limit=10)",
        ["GenericApiPostBody"] = "Corpo POST",
        ["GenericApiPostBodyDesc"] = "Corpo della richiesta per POST/PUT/PATCH. Usa [SEARCH] per il termine di ricerca.",
        ["GenericApiContentType"] = "Tipo di Contenuto",
        ["GenericApiContentTypeDesc"] = "Header Content-Type per il corpo della richiesta (es. application/json)",
        ["GenericApiCustomHeaders"] = "Header Personalizzati",
        ["GenericApiCustomHeadersDesc"] = "Header aggiuntivi, uno per riga (formato: Nome-Header: valore)",
        ["GenericApiResultJsonPath"] = "Percorso JSON Risultato",
        ["GenericApiResultJsonPathDesc"] = "Percorso JSON all'array dei risultati (es. data.results)",
        ["GenericApiResultTitleProperty"] = "Propriet\u00e0 Titolo",
        ["GenericApiResultTitlePropertyDesc"] = "Nome propriet\u00e0 JSON per il titolo del risultato",
        ["GenericApiResultDescriptionProperty"] = "Propriet\u00e0 Descrizione",
        ["GenericApiResultDescriptionPropertyDesc"] = "Nome propriet\u00e0 JSON per la descrizione del risultato",
        ["GenericApiResultUrlProperty"] = "Propriet\u00e0 URL",
        ["GenericApiResultUrlPropertyDesc"] = "Nome propriet\u00e0 JSON per l'URL del risultato",
        ["GenericApiTimeout"] = "Timeout (secondi)",
        ["GenericApiTimeoutDesc"] = "Timeout della richiesta in secondi (1-300)",
        ["GenericApiError"] = "Errore API",
        ["GenericApiRawResponse"] = "Risposta Grezza",
        ["GenericApiMetaQuery"] = "Query",
        ["GenericApiActionOpenUrl"] = "Apri URL",
        ["GenericApiActionOpenUrlDesc"] = "Apri URL del risultato nel browser",
        ["GenericApiActionCopyJson"] = "Copia come JSON",
        ["GenericApiActionCopyJsonDesc"] = "Copia dati del risultato come JSON",
        ["GenericApiActionCopyUrl"] = "Copia URL",
        ["GenericApiActionCopyUrlDesc"] = "Copia URL negli appunti",

        // === Connector: IMAP ===
        ["ImapConnectorName"] = "Email IMAP",
        ["ImapConnectorDescription"] = "Cerca email tramite protocollo IMAP. Supporta OAuth2 e autenticazione con password.",
        ["ImapServer"] = "Server IMAP",
        ["ImapServerDesc"] = "Nome host del server IMAP (es. imap.gmail.com, outlook.office365.com)",
        ["ImapPort"] = "Porta",
        ["ImapPortDesc"] = "Porta del server IMAP (normalmente 993 per SSL/TLS, 143 per STARTTLS)",
        ["ImapEmailAddress"] = "Indirizzo Email",
        ["ImapEmailAddressDesc"] = "Il tuo indirizzo email per l'autenticazione",
        ["ImapAuthType"] = "Tipo di Autenticazione",
        ["ImapAuthTypeDesc"] = "Metodo di autenticazione: Password o OAuth2",
        ["ImapPassword"] = "Password",
        ["ImapPasswordDesc"] = "Password o password specifica per app per l'autenticazione",
        ["ImapOAuth2Token"] = "Token di Accesso OAuth2",
        ["ImapOAuth2TokenDesc"] = "Token di accesso OAuth2 per l'autenticazione (richiesto se il tipo di auth \u00e8 OAuth2)",
        ["ImapEncryption"] = "Crittografia",
        ["ImapEncryptionDesc"] = "Metodo di crittografia: SslTls (consigliato), StartTls o None",
        ["ImapFolderName"] = "Cartella",
        ["ImapFolderNameDesc"] = "Cartella email da cercare (es. INBOX, Sent, Archive)",
        ["ImapMaxResults"] = "Risultati Massimi",
        ["ImapMaxResultsDesc"] = "Numero massimo di email da restituire (1-500)",
        ["ImapMaxDaysBack"] = "Giorni Massimi Indietro",
        ["ImapMaxDaysBackDesc"] = "Quanti giorni indietro cercare email (1-365)",
        ["ImapNoSubject"] = "(Nessun Oggetto)",
        ["ImapError"] = "Errore IMAP",
        ["ImapErrorDesc"] = "Errore di connessione al server IMAP",
        ["ImapMetaFrom"] = "Da",
        ["ImapMetaFromEmail"] = "Da (Email)",
        ["ImapMetaSubject"] = "Oggetto",
        ["ImapMetaDate"] = "Data",
        ["ImapMetaHasAttachments"] = "Allegati",
        ["ImapMetaFolder"] = "Cartella",
        ["ImapActionCopyBody"] = "Copia Corpo",
        ["ImapActionCopyBodyDesc"] = "Copia corpo dell'email negli appunti",
        ["ImapActionCopySender"] = "Copia Mittente",
        ["ImapActionCopySenderDesc"] = "Copia indirizzo email del mittente negli appunti",
    };
}
