// Meta Search and Control Center (c) 2026 Dennis Michael Heine
namespace MSCC.Localization;

/// <summary>
/// Traducciones en espa\u00f1ol.
/// </summary>
public static class Strings_es
{
    public static Dictionary<string, string> Resources { get; } = new()
    {
        // Application
        ["AppTitle"] = "MSCC - Centro de Comando de Meta B\u00fasqueda",
        ["Ready"] = "Listo",
        ["Error"] = "Error",
        ["Warning"] = "Advertencia",
        ["Success"] = "\u00c9xito",
        ["Cancel"] = "Cancelar",
        ["Save"] = "Guardar",
        ["Delete"] = "Eliminar",
        ["Edit"] = "Editar",
        ["Add"] = "A\u00f1adir",
        ["Close"] = "Cerrar",
        ["Yes"] = "S\u00ed",
        ["No"] = "No",
        ["OK"] = "Aceptar",

        // Menu
        ["MenuFile"] = "Archivo",
        ["MenuExit"] = "Salir",
        ["MenuPlugins"] = "Plugins",
        ["MenuScriptManager"] = "Gestor de Scripts...",
        ["MenuReloadScripts"] = "Recargar Scripts",
        ["MenuSettings"] = "Configuraci\u00f3n...",
        ["MenuHelp"] = "Ayuda",
        ["MenuAbout"] = "Acerca de MSCC",

        // Search
        ["Search"] = "Buscar",
        ["SearchResults"] = "Resultados de B\u00fasqueda",
        ["Searching"] = "Buscando...",
        ["SearchCompleted"] = "B\u00fasqueda completada",
        ["NoResults"] = "No se encontraron resultados",
        ["ResultsFound"] = "{0} resultados encontrados",
        ["Source"] = "Fuente",

        // DataSources
        ["DataSources"] = "Fuentes de Datos",
        ["NewDataSource"] = "Nueva Fuente de Datos",
        ["EditDataSource"] = "Editar Fuente de Datos",
        ["DeleteDataSource"] = "Eliminar Fuente de Datos",
        ["DataSourceName"] = "Nombre",
        ["ConnectorType"] = "Tipo de Conector",
        ["Configuration"] = "Configuraci\u00f3n",
        ["Enabled"] = "Activado",
        ["NoDataSourcesSelected"] = "No hay fuentes de datos seleccionadas o disponibles",

        // Groups
        ["Groups"] = "Grupos",
        ["NewGroup"] = "Nuevo Grupo",
        ["EditGroup"] = "Editar Grupo",
        ["DeleteGroup"] = "Eliminar Grupo",
        ["GroupName"] = "Nombre",
        ["GroupColor"] = "Color",
        ["NoGroup"] = "(Sin Grupo)",

        // Details
        ["DetailView"] = "Vista de Detalles",
        ["SelectResultForDetails"] = "Seleccione un resultado para ver los detalles.",
        ["Open"] = "Abrir",
        ["OpenFolder"] = "Abrir Carpeta",
        ["CopyPath"] = "Copiar Ruta",

        // Labels
        ["AddLabel"] = "A\u00f1adir Etiqueta",
        ["SelectResultFirst"] = "Seleccione primero un resultado",
        ["KeywordSearch"] = "B\u00fasqueda por Palabra Clave",
        ["SearchByKeyword"] = "Buscar por Palabra Clave",
        ["CurrentQuery"] = "Consulta Actual",
        ["SavedQueries"] = "Consultas Guardadas",
        ["Load"] = "Cargar",
        ["Labels"] = "Etiquetas",

        // Script Editor
        ["ScriptEditor"] = "Editor de Scripts",
        ["ScriptManager"] = "Gestor de Scripts",
        ["NewScript"] = "Nuevo Script",
        ["Compile"] = "Compilar",
        ["Validate"] = "Validar",
        ["Insert"] = "Insertar",
        ["Errors"] = "Errores",
        ["Warnings"] = "Advertencias",
        ["Line"] = "L\u00ednea",
        ["Column"] = "Columna",
        ["CompileSuccess"] = "Compilaci\u00f3n exitosa - Conector registrado",
        ["CompileFailed"] = "Compilaci\u00f3n fallida - {0} errores",

        // Settings
        ["Settings"] = "Configuraci\u00f3n",
        ["Language"] = "Idioma",
        ["SelectLanguage"] = "Seleccionar Idioma",
        ["RestartRequired"] = "Algunos cambios requieren reiniciar la aplicaci\u00f3n.",
        ["General"] = "General",
        ["Appearance"] = "Apariencia",

        // Validation
        ["FieldRequired"] = "El campo '{0}' es obligatorio.",
        ["InvalidValue"] = "Valor inv\u00e1lido",
        ["ValidationError"] = "Error de Validaci\u00f3n",

        // Status
        ["Loading"] = "Cargando...",
        ["Saving"] = "Guardando...",
        ["Compiling"] = "Compilando...",
        ["ScriptConnectorsLoaded"] = "{0} conectores de script cargados",
        ["DataSourceCreated"] = "Fuente de datos '{0}' creada",
        ["DataSourceUpdated"] = "Fuente de datos '{0}' actualizada",
        ["DataSourceDeleted"] = "Fuente de datos '{0}' eliminada",
        ["GroupCreated"] = "Grupo '{0}' creado",
        ["GroupUpdated"] = "Grupo '{0}' actualizado",
        ["GroupDeleted"] = "Grupo '{0}' eliminado",

        // Confirmation dialogs
        ["ConfirmDelete"] = "\u00bfEst\u00e1 seguro de que desea eliminar '{0}'?",
        ["ConfirmDeleteDataSource"] = "\u00bfRealmente desea eliminar la fuente de datos '{0}'?",
        ["ConfirmDeleteGroup"] = "\u00bfRealmente desea eliminar el grupo '{0}'?\n\nLas fuentes de datos en este grupo no ser\u00e1n eliminadas.",

        // === Connector: FileSystem ===
        ["Connector_FileSystem_Name"] = "Sistema de Archivos",
        ["Connector_FileSystem_Description"] = "Busca archivos y carpetas en el sistema de archivos local.",
        ["Connector_FileSystem_BasePath"] = "Ruta Base",
        ["Connector_FileSystem_BasePath_Desc"] = "La ruta de la carpeta a buscar.",
        ["Connector_FileSystem_SearchPattern"] = "Patr\u00f3n de B\u00fasqueda",
        ["Connector_FileSystem_SearchPattern_Desc"] = "Patr\u00f3n de archivo (ej. *.txt, *.pdf)",
        ["Connector_FileSystem_IncludeSubdirs"] = "Incluir Subcarpetas",
        ["Connector_FileSystem_IncludeSubdirs_Desc"] = "Especifica si se deben buscar subcarpetas.",
        ["Connector_FileSystem_Open"] = "Abrir",
        ["Connector_FileSystem_Open_Desc"] = "Abrir archivo con programa predeterminado",
        ["Connector_FileSystem_OpenFolder"] = "Abrir Carpeta",
        ["Connector_FileSystem_OpenFolder_Desc"] = "Abrir carpeta contenedora",
        ["Connector_FileSystem_CopyPath"] = "Copiar Ruta",
        ["Connector_FileSystem_CopyPath_Desc"] = "Copiar ruta de archivo al portapapeles",
        ["Connector_FileSystem_Path"] = "Ruta",
        ["Connector_FileSystem_Size"] = "Tama\u00f1o",
        ["Connector_FileSystem_Created"] = "Creado",
        ["Connector_FileSystem_Modified"] = "Modificado",
        ["Connector_FileSystem_Type"] = "Tipo",

        // === Connector: DuckDuckGo ===
        ["Connector_DuckDuckGo_Name"] = "B\u00fasqueda Web DuckDuckGo",
        ["Connector_DuckDuckGo_Description"] = "Realiza b\u00fasquedas web a trav\u00e9s de DuckDuckGo.",
        ["Connector_DuckDuckGo_MaxResults"] = "Resultados M\u00e1ximos",
        ["Connector_DuckDuckGo_MaxResults_Desc"] = "N\u00famero de resultados de b\u00fasqueda a devolver (1-30).",
        ["Connector_DuckDuckGo_Region"] = "Regi\u00f3n",
        ["Connector_DuckDuckGo_Region_Desc"] = "Configuraci\u00f3n regional para resultados (ej. 'es-es' para Espa\u00f1a, 'wt-wt' para mundial).",
        ["Connector_DuckDuckGo_SafeSearch"] = "B\u00fasqueda Segura",
        ["Connector_DuckDuckGo_SafeSearch_Desc"] = "Activa el filtro de b\u00fasqueda segura para resultados familiares.",
        ["Connector_DuckDuckGo_OpenBrowser"] = "Abrir en Navegador",
        ["Connector_DuckDuckGo_OpenBrowser_Desc"] = "Abrir p\u00e1gina web en navegador predeterminado",
        ["Connector_DuckDuckGo_CopyUrl"] = "Copiar URL",
        ["Connector_DuckDuckGo_CopyUrl_Desc"] = "Copiar URL al portapapeles",
        ["Connector_DuckDuckGo_SearchMore"] = "Buscar en DuckDuckGo",
        ["Connector_DuckDuckGo_SearchMore_Desc"] = "Mostrar m\u00e1s resultados en DuckDuckGo",
        ["Connector_DuckDuckGo_WebResult"] = "Resultado de B\u00fasqueda Web",
        ["Connector_DuckDuckGo_Position"] = "Posici\u00f3n",

        // === Connector: Microsoft 365 ===
        ["Connector_M365_Name"] = "Microsoft 365",
        ["Connector_M365_Description"] = "Busca en Microsoft 365: Calendario, ToDo, Correos y OneNote.",
        ["Connector_M365_ClientId"] = "ID de Cliente (App-ID)",
        ["Connector_M365_ClientId_Desc"] = "El ID de aplicaci\u00f3n (Cliente) del registro de la aplicaci\u00f3n Azure.",
        ["Connector_M365_TenantId"] = "ID de Tenant",
        ["Connector_M365_TenantId_Desc"] = "El ID de Tenant (o 'common' para multi-tenant, 'consumers' para cuentas personales).",
        ["Connector_M365_SearchCalendar"] = "Buscar Calendario",
        ["Connector_M365_SearchCalendar_Desc"] = "Incluir eventos de calendario en la b\u00fasqueda.",
        ["Connector_M365_SearchToDo"] = "Buscar ToDo",
        ["Connector_M365_SearchToDo_Desc"] = "Incluir tareas de Microsoft ToDo en la b\u00fasqueda.",
        ["Connector_M365_SearchMail"] = "Buscar Correo",
        ["Connector_M365_SearchMail_Desc"] = "Incluir correos electr\u00f3nicos en la b\u00fasqueda.",
        ["Connector_M365_SearchOneNote"] = "Buscar OneNote",
        ["Connector_M365_SearchOneNote_Desc"] = "Incluir p\u00e1ginas de OneNote en la b\u00fasqueda.",
        ["Connector_M365_MaxDaysBack"] = "D\u00edas M\u00e1ximos Atr\u00e1s",
        ["Connector_M365_MaxDaysBack_Desc"] = "Cu\u00e1ntos d\u00edas atr\u00e1s buscar eventos de calendario y correos.",
        ["Connector_M365_OpenOutlook"] = "Abrir en Outlook",
        ["Connector_M365_OpenOutlook_Desc"] = "Abrir en Outlook Web",
        ["Connector_M365_OpenToDo"] = "Abrir en ToDo",
        ["Connector_M365_OpenToDo_Desc"] = "Abrir tarea en Microsoft ToDo",
        ["Connector_M365_OpenOneNote"] = "Abrir en OneNote",
        ["Connector_M365_OpenOneNote_Desc"] = "Abrir p\u00e1gina en OneNote",
        ["Connector_M365_CopyLink"] = "Copiar Enlace",
        ["Connector_M365_CopyLink_Desc"] = "Copiar enlace al portapapeles",
        ["Connector_M365_OpenBrowser"] = "Abrir en Navegador",
        ["Connector_M365_OpenBrowser_Desc"] = "Abrir en navegador predeterminado",
        ["Connector_M365_CalendarEntry"] = "Entrada de Calendario",
        ["Connector_M365_Task"] = "Tarea",
        ["Connector_M365_Email"] = "Correo Electr\u00f3nico",
        ["Connector_M365_OneNotePage"] = "P\u00e1gina de OneNote",
        ["Connector_M365_Subject"] = "Asunto",
        ["Connector_M365_Start"] = "Inicio",
        ["Connector_M365_End"] = "Fin",
        ["Connector_M365_Location"] = "Ubicaci\u00f3n",
        ["Connector_M365_Organizer"] = "Organizador",
        ["Connector_M365_List"] = "Lista",
        ["Connector_M365_Status"] = "Estado",
        ["Connector_M365_Priority"] = "Prioridad",
        ["Connector_M365_DueDate"] = "Fecha de Vencimiento",
        ["Connector_M365_Notes"] = "Notas",
        ["Connector_M365_From"] = "De",
        ["Connector_M365_Received"] = "Recibido",
        ["Connector_M365_Attachments"] = "Adjuntos",
        ["Connector_M365_Preview"] = "Vista Previa",
        ["Connector_M365_Title"] = "T\u00edtulo",
        ["Connector_M365_Section"] = "Secci\u00f3n",

        // === Connector: SQL Database ===
        ["Connector_SQL_Name"] = "Base de Datos SQL",
        ["Connector_SQL_Description"] = "Busca en bases de datos SQL (MySQL, MSSQL, PostgreSQL).",
        ["Connector_SQL_ConnectionString"] = "Cadena de Conexi\u00f3n",
        ["Connector_SQL_ConnectionString_Desc"] = "Cadena de conexi\u00f3n a la base de datos (ej. 'Server=localhost;Database=mydb;User Id=user;Password=pass;')",
        ["Connector_SQL_DatabaseType"] = "Tipo de Base de Datos",
        ["Connector_SQL_DatabaseType_Desc"] = "Tipo de base de datos: MSSQL, MySQL o PostgreSQL",
        ["Connector_SQL_Tables"] = "Tablas",
        ["Connector_SQL_Tables_Desc"] = "Lista de tablas separadas por comas, o '*' para todas. Se ignora si se proporciona una consulta personalizada.",
        ["Connector_SQL_CustomQuery"] = "Consulta SQL Personalizada",
        ["Connector_SQL_CustomQuery_Desc"] = "Opcional: Sentencia SELECT personalizada. Use @SearchTerm como marcador para el t\u00e9rmino de b\u00fasqueda.",
        ["Connector_SQL_CopyJson"] = "Copiar como JSON",
        ["Connector_SQL_CopyJson_Desc"] = "Copiar registro como JSON al portapapeles",
        ["Connector_SQL_CopyInsert"] = "Copiar como INSERT",
        ["Connector_SQL_CopyInsert_Desc"] = "Copiar como sentencia SQL INSERT",
        ["Connector_SQL_MatchesIn"] = "Coincidencias en",
        ["Connector_SQL_Record"] = "Registro",

        // === Connector: OpenAI ===
        ["OpenAiConnectorName"] = "API OpenAI",
        ["OpenAiConnectorDescription"] = "Consulta APIs de IA compatibles con OpenAI (ChatGPT, LLMs locales, etc.).",
        ["OpenAiApiEndpoint"] = "Endpoint de API",
        ["OpenAiApiEndpointDesc"] = "La URL del endpoint de API (ej. https://api.openai.com/v1/chat/completions)",
        ["OpenAiApiKey"] = "Clave de API",
        ["OpenAiApiKeyDesc"] = "Su token de autenticaci\u00f3n de API.",
        ["OpenAiModel"] = "Modelo",
        ["OpenAiModelDesc"] = "El modelo de IA a utilizar (ej. gpt-3.5-turbo, gpt-4, llama2).",
        ["OpenAiSystemPrompt"] = "Prompt del Sistema",
        ["OpenAiSystemPromptDesc"] = "Prompt opcional del sistema para definir el comportamiento de la IA.",
        ["OpenAiMaxTokens"] = "Tokens M\u00e1ximos",
        ["OpenAiMaxTokensDesc"] = "N\u00famero m\u00e1ximo de tokens en la respuesta (1-128000).",
        ["OpenAiTemperature"] = "Temperatura",
        ["OpenAiTemperatureDesc"] = "Creatividad de las respuestas (0.0 = determinista, 2.0 = muy creativo).",
        ["OpenAiResponse"] = "Respuesta de IA",
        ["OpenAiError"] = "Error de API",
        ["OpenAiErrorDesc"] = "Error durante la solicitud de API",
        ["OpenAiMetaModel"] = "Modelo",
        ["OpenAiMetaPromptTokens"] = "Tokens de Prompt",
        ["OpenAiMetaCompletionTokens"] = "Tokens de Respuesta",
        ["OpenAiMetaTotalTokens"] = "Tokens Totales",
        ["OpenAiMetaFinishReason"] = "Raz\u00f3n de Finalizaci\u00f3n",
        ["OpenAiMetaQuery"] = "Consulta",
        ["OpenAiActionCopyResponse"] = "Copiar Respuesta",
        ["OpenAiActionCopyResponseDesc"] = "Copiar la respuesta de IA al portapapeles",
        ["OpenAiActionCopyQuery"] = "Copiar Consulta",
        ["OpenAiActionCopyQueryDesc"] = "Copiar la consulta original al portapapeles",

        // === Connector: Generic API ===
        ["GenericApiConnectorName"] = "API Gen\u00e9rica",
        ["GenericApiConnectorDescription"] = "Conecta con cualquier API REST con autenticaci\u00f3n flexible y ubicaci\u00f3n de par\u00e1metros de b\u00fasqueda.",
        ["GenericApiEndpoint"] = "Endpoint de API",
        ["GenericApiEndpointDesc"] = "La URL base de la API. Use [SEARCH] como marcador para el t\u00e9rmino de b\u00fasqueda.",
        ["GenericApiHttpMethod"] = "M\u00e9todo HTTP",
        ["GenericApiHttpMethodDesc"] = "M\u00e9todo HTTP a utilizar: GET, POST, PUT, PATCH, DELETE",
        ["GenericApiAuthType"] = "Tipo de Autenticaci\u00f3n",
        ["GenericApiAuthTypeDesc"] = "M\u00e9todo de autenticaci\u00f3n: None, Header, Bearer, OAuth2, JWT, Query, Post",
        ["GenericApiAuthHeaderName"] = "Nombre del Header de Auth",
        ["GenericApiAuthHeaderNameDesc"] = "Nombre del header de autenticaci\u00f3n (ej. Authorization, X-API-Key)",
        ["GenericApiAuthHeaderValue"] = "Valor del Header de Auth",
        ["GenericApiAuthHeaderValueDesc"] = "Valor para el header de autenticaci\u00f3n",
        ["GenericApiAuthToken"] = "Token de Auth",
        ["GenericApiAuthTokenDesc"] = "Token de autenticaci\u00f3n para Bearer/JWT, o key=value para autenticaci\u00f3n por par\u00e1metro Query/Post",
        ["GenericApiOAuth2TokenEndpoint"] = "Endpoint de Token OAuth2",
        ["GenericApiOAuth2TokenEndpointDesc"] = "URL para obtener el token de acceso OAuth2",
        ["GenericApiOAuth2ClientId"] = "Client ID OAuth2",
        ["GenericApiOAuth2ClientIdDesc"] = "ID de cliente para autenticaci\u00f3n OAuth2",
        ["GenericApiOAuth2ClientSecret"] = "Client Secret OAuth2",
        ["GenericApiOAuth2ClientSecretDesc"] = "Secreto de cliente para autenticaci\u00f3n OAuth2",
        ["GenericApiOAuth2Scope"] = "Scope OAuth2",
        ["GenericApiOAuth2ScopeDesc"] = "Scope de OAuth2 (opcional)",
        ["GenericApiQueryParameters"] = "Par\u00e1metros de Query",
        ["GenericApiQueryParametersDesc"] = "Par\u00e1metros de query URL. Use [SEARCH] para el t\u00e9rmino de b\u00fasqueda (ej. q=[SEARCH]&limit=10)",
        ["GenericApiPostBody"] = "Cuerpo POST",
        ["GenericApiPostBodyDesc"] = "Cuerpo de la solicitud para POST/PUT/PATCH. Use [SEARCH] para el t\u00e9rmino de b\u00fasqueda.",
        ["GenericApiContentType"] = "Tipo de Contenido",
        ["GenericApiContentTypeDesc"] = "Header Content-Type para el cuerpo de la solicitud (ej. application/json)",
        ["GenericApiCustomHeaders"] = "Headers Personalizados",
        ["GenericApiCustomHeadersDesc"] = "Headers adicionales, uno por l\u00ednea (formato: Nombre-Header: valor)",
        ["GenericApiResultJsonPath"] = "Ruta JSON de Resultado",
        ["GenericApiResultJsonPathDesc"] = "Ruta JSON al array de resultados (ej. data.results)",
        ["GenericApiResultTitleProperty"] = "Propiedad de T\u00edtulo",
        ["GenericApiResultTitlePropertyDesc"] = "Nombre de propiedad JSON para el t\u00edtulo del resultado",
        ["GenericApiResultDescriptionProperty"] = "Propiedad de Descripci\u00f3n",
        ["GenericApiResultDescriptionPropertyDesc"] = "Nombre de propiedad JSON para la descripci\u00f3n del resultado",
        ["GenericApiResultUrlProperty"] = "Propiedad de URL",
        ["GenericApiResultUrlPropertyDesc"] = "Nombre de propiedad JSON para la URL del resultado",
        ["GenericApiTimeout"] = "Timeout (segundos)",
        ["GenericApiTimeoutDesc"] = "Timeout de solicitud en segundos (1-300)",
        ["GenericApiError"] = "Error de API",
        ["GenericApiRawResponse"] = "Respuesta Sin Procesar",
        ["GenericApiMetaQuery"] = "Consulta",
        ["GenericApiActionOpenUrl"] = "Abrir URL",
        ["GenericApiActionOpenUrlDesc"] = "Abrir URL del resultado en el navegador",
        ["GenericApiActionCopyJson"] = "Copiar como JSON",
        ["GenericApiActionCopyJsonDesc"] = "Copiar datos del resultado como JSON",
        ["GenericApiActionCopyUrl"] = "Copiar URL",
        ["GenericApiActionCopyUrlDesc"] = "Copiar URL al portapapeles",

        // === Connector: IMAP ===
        ["ImapConnectorName"] = "Email IMAP",
        ["ImapConnectorDescription"] = "Busca correos electr\u00f3nicos a trav\u00e9s del protocolo IMAP. Soporta OAuth2 y autenticaci\u00f3n por contrase\u00f1a.",
        ["ImapServer"] = "Servidor IMAP",
        ["ImapServerDesc"] = "Nombre de host del servidor IMAP (ej. imap.gmail.com, outlook.office365.com)",
        ["ImapPort"] = "Puerto",
        ["ImapPortDesc"] = "Puerto del servidor IMAP (normalmente 993 para SSL/TLS, 143 para STARTTLS)",
        ["ImapEmailAddress"] = "Direcci\u00f3n de Email",
        ["ImapEmailAddressDesc"] = "Su direcci\u00f3n de email para autenticaci\u00f3n",
        ["ImapAuthType"] = "Tipo de Autenticaci\u00f3n",
        ["ImapAuthTypeDesc"] = "M\u00e9todo de autenticaci\u00f3n: Password o OAuth2",
        ["ImapPassword"] = "Contrase\u00f1a",
        ["ImapPasswordDesc"] = "Contrase\u00f1a o contrase\u00f1a espec\u00edfica de aplicaci\u00f3n para autenticaci\u00f3n",
        ["ImapOAuth2Token"] = "Token de Acceso OAuth2",
        ["ImapOAuth2TokenDesc"] = "Token de acceso OAuth2 para autenticaci\u00f3n (requerido si el tipo de auth es OAuth2)",
        ["ImapEncryption"] = "Cifrado",
        ["ImapEncryptionDesc"] = "M\u00e9todo de cifrado: SslTls (recomendado), StartTls o None",
        ["ImapFolderName"] = "Carpeta",
        ["ImapFolderNameDesc"] = "Carpeta de correo a buscar (ej. INBOX, Sent, Archive)",
        ["ImapMaxResults"] = "Resultados M\u00e1ximos",
        ["ImapMaxResultsDesc"] = "N\u00famero m\u00e1ximo de correos a devolver (1-500)",
        ["ImapMaxDaysBack"] = "D\u00edas M\u00e1ximos Atr\u00e1s",
        ["ImapMaxDaysBackDesc"] = "Cu\u00e1ntos d\u00edas atr\u00e1s buscar correos (1-365)",
        ["ImapNoSubject"] = "(Sin Asunto)",
        ["ImapError"] = "Error IMAP",
        ["ImapErrorDesc"] = "Error al conectar con el servidor IMAP",
        ["ImapMetaFrom"] = "De",
        ["ImapMetaFromEmail"] = "De (Email)",
        ["ImapMetaSubject"] = "Asunto",
        ["ImapMetaDate"] = "Fecha",
        ["ImapMetaHasAttachments"] = "Adjuntos",
        ["ImapMetaFolder"] = "Carpeta",
        ["ImapActionCopyBody"] = "Copiar Cuerpo",
        ["ImapActionCopyBodyDesc"] = "Copiar cuerpo del correo al portapapeles",
        ["ImapActionCopySender"] = "Copiar Remitente",
        ["ImapActionCopySenderDesc"] = "Copiar direcci\u00f3n de email del remitente al portapapeles",
    };
}
