// Meta Search and Control Center (c) 2026 Dennis Michael Heine
namespace MSCC.Localization;

/// <summary>
/// Deutsche \u00dcbersetzungen.
/// </summary>
public static class Strings_de
{
    public static Dictionary<string, string> Resources { get; } = new()
    {
        // Application
        ["AppTitle"] = "MSCC - Meta Search Command Center",
        ["Ready"] = "Bereit",
        ["Error"] = "Fehler",
        ["Warning"] = "Warnung",
        ["Success"] = "Erfolg",
        ["Cancel"] = "Abbrechen",
        ["Save"] = "Speichern",
        ["Delete"] = "L\u00f6schen",
        ["Edit"] = "Bearbeiten",
        ["Add"] = "Hinzuf\u00fcgen",
        ["Close"] = "Schlie\u00dfen",
        ["Yes"] = "Ja",
        ["No"] = "Nein",
        ["OK"] = "OK",

        // Menu
        ["MenuFile"] = "Datei",
        ["MenuExit"] = "Beenden",
        ["MenuPlugins"] = "Plugins",
        ["MenuScriptManager"] = "Script Manager...",
        ["MenuReloadScripts"] = "Scripts neu laden",
        ["MenuSettings"] = "Einstellungen...",
        ["MenuHelp"] = "Hilfe",
        ["MenuAbout"] = "\u00dcber MSCC",

        // Search
        ["Search"] = "Suchen",
        ["SearchResults"] = "Suchergebnisse",
        ["Searching"] = "Suche l\u00e4uft...",
        ["SearchCompleted"] = "Suche abgeschlossen",
        ["NoResults"] = "Keine Ergebnisse gefunden",
        ["ResultsFound"] = "{0} Ergebnisse gefunden",
        ["Source"] = "Quelle",

        // DataSources
        ["DataSources"] = "Datenquellen",
        ["NewDataSource"] = "Neue Datenquelle",
        ["EditDataSource"] = "Datenquelle bearbeiten",
        ["DeleteDataSource"] = "Datenquelle l\u00f6schen",
        ["DataSourceName"] = "Name",
        ["ConnectorType"] = "Konnektor-Typ",
        ["Configuration"] = "Konfiguration",
        ["Enabled"] = "Aktiviert",
        ["NoDataSourcesSelected"] = "Keine Datenquellen ausgew\u00e4hlt oder verf\u00fcgbar",

        // Groups
        ["Groups"] = "Gruppen",
        ["NewGroup"] = "Neue Gruppe",
        ["EditGroup"] = "Gruppe bearbeiten",
        ["DeleteGroup"] = "Gruppe l\u00f6schen",
        ["GroupName"] = "Name",
        ["GroupColor"] = "Farbe",
        ["NoGroup"] = "(Keine Gruppe)",

        // Details
        ["DetailView"] = "Detailansicht",
        ["SelectResultForDetails"] = "W\u00e4hlen Sie ein Suchergebnis aus, um Details anzuzeigen.",
        ["Open"] = "\u00d6ffnen",
        ["OpenFolder"] = "Ordner \u00f6ffnen",
        ["CopyPath"] = "Pfad kopieren",

        // Labels
        ["AddLabel"] = "Label hinzuf\u00fcgen",
        ["SelectResultFirst"] = "W\u00e4hlen Sie zuerst ein Ergebnis aus",
        ["KeywordSearch"] = "Keyword-Suche",
        ["SearchByKeyword"] = "Nach Keyword suchen",
        ["CurrentQuery"] = "Aktuelle Abfrage",
        ["SavedQueries"] = "Gespeicherte Abfragen",
        ["Load"] = "Laden",
        ["Labels"] = "Labels",

        // Script Editor
        ["ScriptEditor"] = "Script Editor",
        ["ScriptManager"] = "Script Manager",
        ["NewScript"] = "Neues Script",
        ["Compile"] = "Kompilieren",
        ["Validate"] = "Validieren",
        ["Insert"] = "Einf\u00fcgen",
        ["Errors"] = "Fehler",
        ["Warnings"] = "Warnungen",
        ["Line"] = "Zeile",
        ["Column"] = "Spalte",
        ["CompileSuccess"] = "Kompilierung erfolgreich - Konnektor registriert",
        ["CompileFailed"] = "Kompilierung fehlgeschlagen - {0} Fehler",

        // Settings
        ["Settings"] = "Einstellungen",
        ["Language"] = "Sprache",
        ["SelectLanguage"] = "Sprache ausw\u00e4hlen",
        ["RestartRequired"] = "Einige \u00c4nderungen erfordern einen Neustart.",
        ["General"] = "Allgemein",
        ["Appearance"] = "Darstellung",

        // Validation
        ["FieldRequired"] = "Das Feld '{0}' ist erforderlich.",
        ["InvalidValue"] = "Ung\u00fcltiger Wert",
        ["ValidationError"] = "Validierungsfehler",

        // Status
        ["Loading"] = "Wird geladen...",
        ["Saving"] = "Wird gespeichert...",
        ["Compiling"] = "Kompiliere...",
        ["ScriptConnectorsLoaded"] = "{0} Script-Konnektoren geladen",
        ["DataSourceCreated"] = "Datenquelle '{0}' erstellt",
        ["DataSourceUpdated"] = "Datenquelle '{0}' aktualisiert",
        ["DataSourceDeleted"] = "Datenquelle '{0}' gel\u00f6scht",
        ["GroupCreated"] = "Gruppe '{0}' erstellt",
        ["GroupUpdated"] = "Gruppe '{0}' aktualisiert",
        ["GroupDeleted"] = "Gruppe '{0}' gel\u00f6scht",

        // Confirmation dialogs
        ["ConfirmDelete"] = "M\u00f6chten Sie '{0}' wirklich l\u00f6schen?",
        ["ConfirmDeleteDataSource"] = "M\u00f6chten Sie die Datenquelle '{0}' wirklich l\u00f6schen?",
        ["ConfirmDeleteGroup"] = "M\u00f6chten Sie die Gruppe '{0}' wirklich l\u00f6schen?\n\nDatenquellen in dieser Gruppe werden nicht gel\u00f6scht.",

        // === Connector: FileSystem ===
        ["Connector_FileSystem_Name"] = "Dateisystem",
        ["Connector_FileSystem_Description"] = "Durchsucht Dateien und Ordner im lokalen Dateisystem.",
        ["Connector_FileSystem_BasePath"] = "Basispfad",
        ["Connector_FileSystem_BasePath_Desc"] = "Der Ordnerpfad, der durchsucht werden soll.",
        ["Connector_FileSystem_SearchPattern"] = "Suchmuster",
        ["Connector_FileSystem_SearchPattern_Desc"] = "Dateimuster (z.B. *.txt, *.pdf)",
        ["Connector_FileSystem_IncludeSubdirs"] = "Unterordner einschlie\u00dfen",
        ["Connector_FileSystem_IncludeSubdirs_Desc"] = "Gibt an, ob Unterordner durchsucht werden sollen.",
        ["Connector_FileSystem_Open"] = "\u00d6ffnen",
        ["Connector_FileSystem_Open_Desc"] = "Datei mit Standardprogramm \u00f6ffnen",
        ["Connector_FileSystem_OpenFolder"] = "Ordner \u00f6ffnen",
        ["Connector_FileSystem_OpenFolder_Desc"] = "\u00dcbergeordneten Ordner \u00f6ffnen",
        ["Connector_FileSystem_CopyPath"] = "Pfad kopieren",
        ["Connector_FileSystem_CopyPath_Desc"] = "Dateipfad in Zwischenablage kopieren",
        ["Connector_FileSystem_Path"] = "Pfad",
        ["Connector_FileSystem_Size"] = "Gr\u00f6\u00dfe",
        ["Connector_FileSystem_Created"] = "Erstellt",
        ["Connector_FileSystem_Modified"] = "Ge\u00e4ndert",
        ["Connector_FileSystem_Type"] = "Typ",

        // === Connector: DuckDuckGo ===
        ["Connector_DuckDuckGo_Name"] = "DuckDuckGo Websuche",
        ["Connector_DuckDuckGo_Description"] = "F\u00fchrt Websuchen \u00fcber DuckDuckGo durch.",
        ["Connector_DuckDuckGo_MaxResults"] = "Maximale Ergebnisse",
        ["Connector_DuckDuckGo_MaxResults_Desc"] = "Anzahl der Suchergebnisse, die zur\u00fcckgegeben werden sollen (1-30).",
        ["Connector_DuckDuckGo_Region"] = "Region",
        ["Connector_DuckDuckGo_Region_Desc"] = "Regionseinstellung f\u00fcr Suchergebnisse (z.B. 'de-de' f\u00fcr Deutschland, 'wt-wt' f\u00fcr weltweit).",
        ["Connector_DuckDuckGo_SafeSearch"] = "SafeSearch",
        ["Connector_DuckDuckGo_SafeSearch_Desc"] = "Aktiviert den SafeSearch-Filter f\u00fcr familienfreundliche Ergebnisse.",
        ["Connector_DuckDuckGo_OpenBrowser"] = "Im Browser \u00f6ffnen",
        ["Connector_DuckDuckGo_OpenBrowser_Desc"] = "Webseite im Standard-Browser \u00f6ffnen",
        ["Connector_DuckDuckGo_CopyUrl"] = "URL kopieren",
        ["Connector_DuckDuckGo_CopyUrl_Desc"] = "URL in Zwischenablage kopieren",
        ["Connector_DuckDuckGo_SearchMore"] = "Auf DuckDuckGo suchen",
        ["Connector_DuckDuckGo_SearchMore_Desc"] = "Weitere Ergebnisse auf DuckDuckGo anzeigen",
        ["Connector_DuckDuckGo_WebResult"] = "Websuche-Ergebnis",
        ["Connector_DuckDuckGo_Position"] = "Position",

        // === Connector: Microsoft 365 ===
        ["Connector_M365_Name"] = "Microsoft 365",
        ["Connector_M365_Description"] = "Durchsucht Microsoft 365: Kalender, ToDo, E-Mails und OneNote.",
        ["Connector_M365_ClientId"] = "Client ID (App-ID)",
        ["Connector_M365_ClientId_Desc"] = "Die Application (Client) ID aus der Azure App-Registrierung.",
        ["Connector_M365_TenantId"] = "Tenant ID",
        ["Connector_M365_TenantId_Desc"] = "Die Tenant ID (oder 'common' f\u00fcr Multi-Tenant, 'consumers' f\u00fcr pers\u00f6nliche Konten).",
        ["Connector_M365_SearchCalendar"] = "Kalender durchsuchen",
        ["Connector_M365_SearchCalendar_Desc"] = "Kalendereintr\u00e4ge in die Suche einbeziehen.",
        ["Connector_M365_SearchToDo"] = "ToDo durchsuchen",
        ["Connector_M365_SearchToDo_Desc"] = "Microsoft ToDo Aufgaben in die Suche einbeziehen.",
        ["Connector_M365_SearchMail"] = "E-Mails durchsuchen",
        ["Connector_M365_SearchMail_Desc"] = "E-Mails in die Suche einbeziehen.",
        ["Connector_M365_SearchOneNote"] = "OneNote durchsuchen",
        ["Connector_M365_SearchOneNote_Desc"] = "OneNote-Notizen in die Suche einbeziehen.",
        ["Connector_M365_MaxDaysBack"] = "Maximale Tage zur\u00fcck",
        ["Connector_M365_MaxDaysBack_Desc"] = "Wie viele Tage zur\u00fcck nach Kalendereintr\u00e4gen und E-Mails gesucht werden soll.",
        ["Connector_M365_OpenOutlook"] = "In Outlook \u00f6ffnen",
        ["Connector_M365_OpenOutlook_Desc"] = "In Outlook Web \u00f6ffnen",
        ["Connector_M365_OpenToDo"] = "In ToDo \u00f6ffnen",
        ["Connector_M365_OpenToDo_Desc"] = "Aufgabe in Microsoft ToDo \u00f6ffnen",
        ["Connector_M365_OpenOneNote"] = "In OneNote \u00f6ffnen",
        ["Connector_M365_OpenOneNote_Desc"] = "Seite in OneNote \u00f6ffnen",
        ["Connector_M365_CopyLink"] = "Link kopieren",
        ["Connector_M365_CopyLink_Desc"] = "Link in Zwischenablage kopieren",
        ["Connector_M365_OpenBrowser"] = "Im Browser \u00f6ffnen",
        ["Connector_M365_OpenBrowser_Desc"] = "Im Standard-Browser \u00f6ffnen",
        ["Connector_M365_CalendarEntry"] = "Kalendereintrag",
        ["Connector_M365_Task"] = "Aufgabe",
        ["Connector_M365_Email"] = "E-Mail",
        ["Connector_M365_OneNotePage"] = "OneNote-Seite",
        ["Connector_M365_Subject"] = "Betreff",
        ["Connector_M365_Start"] = "Beginn",
        ["Connector_M365_End"] = "Ende",
        ["Connector_M365_Location"] = "Ort",
        ["Connector_M365_Organizer"] = "Organisator",
        ["Connector_M365_List"] = "Liste",
        ["Connector_M365_Status"] = "Status",
        ["Connector_M365_Priority"] = "Priorit\u00e4t",
        ["Connector_M365_DueDate"] = "F\u00e4llig am",
        ["Connector_M365_Notes"] = "Notizen",
        ["Connector_M365_From"] = "Von",
        ["Connector_M365_Received"] = "Empfangen",
        ["Connector_M365_Attachments"] = "Anh\u00e4nge",
        ["Connector_M365_Preview"] = "Vorschau",
        ["Connector_M365_Title"] = "Titel",
        ["Connector_M365_Section"] = "Abschnitt",

        // === Connector: SQL Database ===
        ["Connector_SQL_Name"] = "SQL-Datenbank",
        ["Connector_SQL_Description"] = "Durchsucht SQL-Datenbanken (MySQL, MSSQL, PostgreSQL).",
        ["Connector_SQL_ConnectionString"] = "Verbindungszeichenfolge",
        ["Connector_SQL_ConnectionString_Desc"] = "Datenbank-Verbindungsstring (z.B. 'Server=localhost;Database=mydb;User Id=user;Password=pass;')",
        ["Connector_SQL_DatabaseType"] = "Datenbanktyp",
        ["Connector_SQL_DatabaseType_Desc"] = "Typ der Datenbank: MSSQL, MySQL oder PostgreSQL",
        ["Connector_SQL_Tables"] = "Tabellen",
        ["Connector_SQL_Tables_Desc"] = "Kommagetrennte Liste der zu durchsuchenden Tabellen, oder '*' f\u00fcr alle Tabellen. Wird ignoriert, wenn eine benutzerdefinierte Abfrage angegeben ist.",
        ["Connector_SQL_CustomQuery"] = "Benutzerdefinierte SQL-Abfrage",
        ["Connector_SQL_CustomQuery_Desc"] = "Optional: Benutzerdefiniertes SELECT-Statement. Verwenden Sie @SearchTerm als Platzhalter f\u00fcr den Suchbegriff.",
        ["Connector_SQL_CopyJson"] = "Als JSON kopieren",
        ["Connector_SQL_CopyJson_Desc"] = "Datensatz als JSON in Zwischenablage kopieren",
        ["Connector_SQL_CopyInsert"] = "Als INSERT kopieren",
        ["Connector_SQL_CopyInsert_Desc"] = "Als SQL INSERT-Statement kopieren",
        ["Connector_SQL_MatchesIn"] = "Treffer in",
        ["Connector_SQL_Record"] = "Datensatz",
    };
}
